<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class GeometryEx
 </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class GeometryEx
 ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../public/docfx.min.css">
      <link rel="stylesheet" href="../public/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      
      
      
  </head>

  <script type="module">
    import options from './../public/main.js'
    import { init } from './../public/docfx.min.js'
    init(options)
  </script>

  <script>
    const theme = localStorage.getItem('theme') || 'auto'
    document.documentElement.setAttribute('data-bs-theme', theme === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : theme)
  </script>


  <body class="tex2jax_ignore" data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../logo.svg" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navpanel" aria-controls="navpanel" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navpanel">
            <div id="navbar">
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="IFoxCAD.Cad.GeometryEx">



  <h1 id="IFoxCAD_Cad_GeometryEx" data-uid="IFoxCAD.Cad.GeometryEx" class="text-break">
    Class GeometryEx
  
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><a class="xref" href="IFoxCAD.html">IFoxCAD</a>.<a class="xref" href="IFoxCAD.Cad.html">Cad</a></dd></dl>
  <dl><dt>Assembly</dt><dd>IFox.CAD.ACAD.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>图形扩展类</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static class GeometryEx</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">GeometryEx</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>






  <h2 class="section" id="methods">Methods
</h2>


  <a id="IFoxCAD_Cad_GeometryEx_ConvexHull_" data-uid="IFoxCAD.Cad.GeometryEx.ConvexHull*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_ConvexHull_System_Collections_Generic_List_Autodesk_AutoCAD_Geometry_Point2d__" data-uid="IFoxCAD.Cad.GeometryEx.ConvexHull(System.Collections.Generic.List{Autodesk.AutoCAD.Geometry.Point2d})">
  ConvexHull(List&lt;Point2d&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>获取点集的凸包</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static List&lt;Point2d?&gt;? ConvexHull(this List&lt;Point2d&gt; points)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>points</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>点集</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>凸包</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_Draw_" data-uid="IFoxCAD.Cad.GeometryEx.Draw*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Draw_Autodesk_AutoCAD_GraphicsInterface_Geometry_Autodesk_AutoCAD_GraphicsInterface_Drawable___" data-uid="IFoxCAD.Cad.GeometryEx.Draw(Autodesk.AutoCAD.GraphicsInterface.Geometry,Autodesk.AutoCAD.GraphicsInterface.Drawable[])">
  Draw(Geometry, params Drawable[])
  
  </h3>

  <div class="markdown level1 summary"><p>重绘</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static void Draw(this Geometry geometry, params Drawable[] drawables)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>geometry</code> <span class="xref">Geometry</span></dt>
    <dd><p>图形界面几何</p>
</dd>
    <dt><code>drawables</code> <span class="xref">Drawable</span>[]</dt>
    <dd><p>可绘制的对象列表</p>
</dd>
  </dl>












  <a id="IFoxCAD_Cad_GeometryEx_Draw_" data-uid="IFoxCAD.Cad.GeometryEx.Draw*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Draw_Autodesk_AutoCAD_GraphicsInterface_Geometry_System_Collections_Generic_IEnumerable_Autodesk_AutoCAD_GraphicsInterface_Drawable__" data-uid="IFoxCAD.Cad.GeometryEx.Draw(Autodesk.AutoCAD.GraphicsInterface.Geometry,System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.GraphicsInterface.Drawable})">
  Draw(Geometry, IEnumerable&lt;Drawable&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>重绘</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static void Draw(this Geometry geometry, IEnumerable&lt;Drawable&gt; drawables)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>geometry</code> <span class="xref">Geometry</span></dt>
    <dd><p>图形界面几何</p>
</dd>
    <dt><code>drawables</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Drawable</span>&gt;</dt>
    <dd><p>可绘制的对象列表</p>
</dd>
  </dl>












  <a id="IFoxCAD_Cad_GeometryEx_GetArea_" data-uid="IFoxCAD.Cad.GeometryEx.GetArea*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_GetArea_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_" data-uid="IFoxCAD.Cad.GeometryEx.GetArea(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d)">
  GetArea(Point2d, Point2d, Point2d)
  
  </h3>

  <div class="markdown level1 summary"><p>计算三点围成的三角形的真实面积</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static double GetArea(this Point2d ptBase, Point2d pt1, Point2d pt2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ptBase</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>pt1</code> <span class="xref">Point2d</span></dt>
    <dd><p>第一点</p>
</dd>
    <dt><code>pt2</code> <span class="xref">Point2d</span></dt>
    <dd><p>第二点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>三点围成的三角形的真实面积</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_GetArea_" data-uid="IFoxCAD.Cad.GeometryEx.GetArea*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_GetArea_Autodesk_AutoCAD_Geometry_Vector2d_Autodesk_AutoCAD_Geometry_Vector2d_" data-uid="IFoxCAD.Cad.GeometryEx.GetArea(Autodesk.AutoCAD.Geometry.Vector2d,Autodesk.AutoCAD.Geometry.Vector2d)">
  GetArea(Vector2d, Vector2d)
  
  </h3>

  <div class="markdown level1 summary"><p>计算两个二维向量围成的平行四边形的真实面积</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static double GetArea(Vector2d vecBase, Vector2d vec)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>vecBase</code> <span class="xref">Vector2d</span></dt>
    <dd><p>基向量</p>
</dd>
    <dt><code>vec</code> <span class="xref">Vector2d</span></dt>
    <dd><p>向量</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>真实面积</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_GetArea_" data-uid="IFoxCAD.Cad.GeometryEx.GetArea*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_GetArea_System_Collections_Generic_IEnumerable_Autodesk_AutoCAD_Geometry_Point2d__" data-uid="IFoxCAD.Cad.GeometryEx.GetArea(System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.Geometry.Point2d})">
  GetArea(IEnumerable&lt;Point2d&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>计算点集的真实面积</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static double GetArea(this IEnumerable&lt;Point2d&gt; pnts)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pnts</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>点集</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>面积</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_GetMinCircle_" data-uid="IFoxCAD.Cad.GeometryEx.GetMinCircle*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_GetMinCircle_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_IFoxCAD_Basal_LoopList_Autodesk_AutoCAD_Geometry_Point2d___" data-uid="IFoxCAD.Cad.GeometryEx.GetMinCircle(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,IFoxCAD.Basal.LoopList{Autodesk.AutoCAD.Geometry.Point2d}@)">
  GetMinCircle(Point2d?, Point2d?, Point2d?, Point2d?, out LoopList&lt;Point2d?&gt;?)
  
  </h3>

  <div class="markdown level1 summary"><p>按四点返回最小包围圆</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static CircularArc2d? GetMinCircle(Point2d? pt1, Point2d? pt2, Point2d? pt3, Point2d? pt4, out LoopList&lt;Point2d?&gt;? ptlst)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pt1</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>pt2</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>pt3</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>pt4</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>ptlst</code> <a class="xref" href="IFoxCAD.Basal.LoopList-1.html">LoopList</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>输出圆上的点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">CircularArc2d</span></dt>
    <dd><p>解析类圆对象</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_GetMinCircle_" data-uid="IFoxCAD.Cad.GeometryEx.GetMinCircle*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_GetMinCircle_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_IFoxCAD_Basal_LoopList_Autodesk_AutoCAD_Geometry_Point2d___" data-uid="IFoxCAD.Cad.GeometryEx.GetMinCircle(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,IFoxCAD.Basal.LoopList{Autodesk.AutoCAD.Geometry.Point2d}@)">
  GetMinCircle(Point2d, Point2d, Point2d, out LoopList&lt;Point2d&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>按三点返回最小包围圆</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static CircularArc2d GetMinCircle(Point2d pt1, Point2d pt2, Point2d pt3, out LoopList&lt;Point2d&gt; ptlst)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pt1</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>pt2</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>pt3</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>ptlst</code> <a class="xref" href="IFoxCAD.Basal.LoopList-1.html">LoopList</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>输出圆上的点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">CircularArc2d</span></dt>
    <dd><p>解析类圆对象</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_GetMinCircle_" data-uid="IFoxCAD.Cad.GeometryEx.GetMinCircle*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_GetMinCircle_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_IFoxCAD_Basal_LoopList_Autodesk_AutoCAD_Geometry_Point2d___" data-uid="IFoxCAD.Cad.GeometryEx.GetMinCircle(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,IFoxCAD.Basal.LoopList{Autodesk.AutoCAD.Geometry.Point2d}@)">
  GetMinCircle(Point2d, Point2d, out LoopList&lt;Point2d&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>按两点返回最小包围圆</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static CircularArc2d GetMinCircle(Point2d pt1, Point2d pt2, out LoopList&lt;Point2d&gt; ptlst)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pt1</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>pt2</code> <span class="xref">Point2d</span></dt>
    <dd><p>基准点</p>
</dd>
    <dt><code>ptlst</code> <a class="xref" href="IFoxCAD.Basal.LoopList-1.html">LoopList</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>输出圆上的点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">CircularArc2d</span></dt>
    <dd><p>解析类圆对象</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_GetMinCircle_" data-uid="IFoxCAD.Cad.GeometryEx.GetMinCircle*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_GetMinCircle_System_Collections_Generic_List_Autodesk_AutoCAD_Geometry_Point2d__IFoxCAD_Basal_LoopList_Autodesk_AutoCAD_Geometry_Point2d___" data-uid="IFoxCAD.Cad.GeometryEx.GetMinCircle(System.Collections.Generic.List{Autodesk.AutoCAD.Geometry.Point2d},IFoxCAD.Basal.LoopList{Autodesk.AutoCAD.Geometry.Point2d}@)">
  GetMinCircle(List&lt;Point2d&gt;, out LoopList&lt;Point2d?&gt;?)
  
  </h3>

  <div class="markdown level1 summary"><p>按点集返回最小包围圆</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static CircularArc2d? GetMinCircle(this List&lt;Point2d&gt; pnts, out LoopList&lt;Point2d?&gt;? ptlst)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pnts</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>点集</p>
</dd>
    <dt><code>ptlst</code> <a class="xref" href="IFoxCAD.Basal.LoopList-1.html">LoopList</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>输出圆上的点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">CircularArc2d</span></dt>
    <dd><p>解析类圆对象</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_GetScaleMatrix_" data-uid="IFoxCAD.Cad.GeometryEx.GetScaleMatrix*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_GetScaleMatrix_Autodesk_AutoCAD_Geometry_Point3d_System_Double_System_Double_System_Double_" data-uid="IFoxCAD.Cad.GeometryEx.GetScaleMatrix(Autodesk.AutoCAD.Geometry.Point3d,System.Double,System.Double,System.Double)">
  GetScaleMatrix(Point3d, double, double, double)
  
  </h3>

  <div class="markdown level1 summary"><p>返回不等比例变换矩阵</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Matrix3d GetScaleMatrix(this Point3d point, double x, double y, double z)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>point</code> <span class="xref">Point3d</span></dt>
    <dd><p>基点</p>
</dd>
    <dt><code>x</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>x方向比例</p>
</dd>
    <dt><code>y</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>y方向比例</p>
</dd>
    <dt><code>z</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>z方向比例</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Matrix3d</span></dt>
    <dd><p>三维矩阵</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_GetSize_" data-uid="IFoxCAD.Cad.GeometryEx.GetSize*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_GetSize_Autodesk_AutoCAD_DatabaseServices_Extents3d_" data-uid="IFoxCAD.Cad.GeometryEx.GetSize(Autodesk.AutoCAD.DatabaseServices.Extents3d)">
  GetSize(Extents3d)
  
  </h3>

  <div class="markdown level1 summary"><p>获取坐标范围的大小</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Size GetSize(this Extents3d ext)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ext</code> <span class="xref">Extents3d</span></dt>
    <dd><p>坐标范围</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.drawing.size">Size</a></dt>
    <dd><p>尺寸对象</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_IsClockWise_" data-uid="IFoxCAD.Cad.GeometryEx.IsClockWise*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_IsClockWise_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_" data-uid="IFoxCAD.Cad.GeometryEx.IsClockWise(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d)">
  IsClockWise(Point2d, Point2d, Point2d)
  
  </h3>

  <div class="markdown level1 summary"><p>判断三点是否为逆时针，也就是说判断三点是否为左转</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static OrientationType IsClockWise(this Point2d ptBase, Point2d pt1, Point2d pt2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ptBase</code> <span class="xref">Point2d</span></dt>
    <dd><p>基点</p>
</dd>
    <dt><code>pt1</code> <span class="xref">Point2d</span></dt>
    <dd><p>第一点</p>
</dd>
    <dt><code>pt2</code> <span class="xref">Point2d</span></dt>
    <dd><p>第二点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="IFoxCAD.Cad.OrientationType.html">OrientationType</a></dt>
    <dd><p>OrientationType 类型值</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_IsClockWise_" data-uid="IFoxCAD.Cad.GeometryEx.IsClockWise*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_IsClockWise_Autodesk_AutoCAD_Geometry_Vector2d_Autodesk_AutoCAD_Geometry_Vector2d_" data-uid="IFoxCAD.Cad.GeometryEx.IsClockWise(Autodesk.AutoCAD.Geometry.Vector2d,Autodesk.AutoCAD.Geometry.Vector2d)">
  IsClockWise(Vector2d, Vector2d)
  
  </h3>

  <div class="markdown level1 summary"><p>判断两个二维向量是否左转</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static OrientationType IsClockWise(Vector2d vecBase, Vector2d vec)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>vecBase</code> <span class="xref">Vector2d</span></dt>
    <dd><p>基向量</p>
</dd>
    <dt><code>vec</code> <span class="xref">Vector2d</span></dt>
    <dd><p>向量</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="IFoxCAD.Cad.OrientationType.html">OrientationType</a></dt>
    <dd><p>OrientationType 类型值</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_IsClockWise_" data-uid="IFoxCAD.Cad.GeometryEx.IsClockWise*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_IsClockWise_System_Collections_Generic_IEnumerable_Autodesk_AutoCAD_Geometry_Point2d__" data-uid="IFoxCAD.Cad.GeometryEx.IsClockWise(System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.Geometry.Point2d})">
  IsClockWise(IEnumerable&lt;Point2d&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>判断点集的点序</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static OrientationType IsClockWise(this IEnumerable&lt;Point2d&gt; pnts)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pnts</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>点集</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="IFoxCAD.Cad.OrientationType.html">OrientationType</a></dt>
    <dd><p>OrientationType 类型值</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_PointOnRegion_" data-uid="IFoxCAD.Cad.GeometryEx.PointOnRegion*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_PointOnRegion_System_Collections_Generic_IEnumerable_Autodesk_AutoCAD_Geometry_Point2d__Autodesk_AutoCAD_Geometry_Point2d_" data-uid="IFoxCAD.Cad.GeometryEx.PointOnRegion(System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.Geometry.Point2d},Autodesk.AutoCAD.Geometry.Point2d)">
  PointOnRegion(IEnumerable&lt;Point2d&gt;, Point2d)
  
  </h3>

  <div class="markdown level1 summary"><p>判断点与多边形的关系</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static PointOnRegionType PointOnRegion(this IEnumerable&lt;Point2d&gt; pts, Point2d pt)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pts</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>多边形顶点集合</p>
</dd>
    <dt><code>pt</code> <span class="xref">Point2d</span></dt>
    <dd><p>点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="IFoxCAD.Cad.PointOnRegionType.html">PointOnRegionType</a></dt>
    <dd><p>点与多边形的关系</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_PointOnRegion_" data-uid="IFoxCAD.Cad.GeometryEx.PointOnRegion*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_PointOnRegion_System_Collections_Generic_IEnumerable_Autodesk_AutoCAD_Geometry_Point3d__Autodesk_AutoCAD_Geometry_Point3d_" data-uid="IFoxCAD.Cad.GeometryEx.PointOnRegion(System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.Geometry.Point3d},Autodesk.AutoCAD.Geometry.Point3d)">
  PointOnRegion(IEnumerable&lt;Point3d&gt;, Point3d)
  
  </h3>

  <div class="markdown level1 summary"><p>判断点与多边形的关系</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static PointOnRegionType PointOnRegion(this IEnumerable&lt;Point3d&gt; pts, Point3d pt)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pts</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Point3d</span>&gt;</dt>
    <dd><p>多边形顶点集合</p>
</dd>
    <dt><code>pt</code> <span class="xref">Point3d</span></dt>
    <dd><p>点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="IFoxCAD.Cad.PointOnRegionType.html">PointOnRegionType</a></dt>
    <dd><p>点与多边形的关系</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_Trans_" data-uid="IFoxCAD.Cad.GeometryEx.Trans*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Trans_Autodesk_AutoCAD_Geometry_Point3d_IFoxCAD_Cad_CoordinateSystemCode_IFoxCAD_Cad_CoordinateSystemCode_" data-uid="IFoxCAD.Cad.GeometryEx.Trans(Autodesk.AutoCAD.Geometry.Point3d,IFoxCAD.Cad.CoordinateSystemCode,IFoxCAD.Cad.CoordinateSystemCode)">
  Trans(Point3d, CoordinateSystemCode, CoordinateSystemCode)
  
  </h3>

  <div class="markdown level1 summary"><p>模拟 trans 函数</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point3d Trans(this Point3d point, CoordinateSystemCode from, CoordinateSystemCode to)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>point</code> <span class="xref">Point3d</span></dt>
    <dd><p>点</p>
</dd>
    <dt><code>from</code> <a class="xref" href="IFoxCAD.Cad.CoordinateSystemCode.html">CoordinateSystemCode</a></dt>
    <dd><p>源坐标系</p>
</dd>
    <dt><code>to</code> <a class="xref" href="IFoxCAD.Cad.CoordinateSystemCode.html">CoordinateSystemCode</a></dt>
    <dd><p>目标坐标系</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point3d</span></dt>
    <dd><p>变换后的点</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_Trans_" data-uid="IFoxCAD.Cad.GeometryEx.Trans*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Trans_Autodesk_AutoCAD_Geometry_Vector3d_IFoxCAD_Cad_CoordinateSystemCode_IFoxCAD_Cad_CoordinateSystemCode_" data-uid="IFoxCAD.Cad.GeometryEx.Trans(Autodesk.AutoCAD.Geometry.Vector3d,IFoxCAD.Cad.CoordinateSystemCode,IFoxCAD.Cad.CoordinateSystemCode)">
  Trans(Vector3d, CoordinateSystemCode, CoordinateSystemCode)
  
  </h3>

  <div class="markdown level1 summary"><p>模拟 trans 函数</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Vector3d Trans(this Vector3d vec, CoordinateSystemCode from, CoordinateSystemCode to)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>vec</code> <span class="xref">Vector3d</span></dt>
    <dd><p>向量</p>
</dd>
    <dt><code>from</code> <a class="xref" href="IFoxCAD.Cad.CoordinateSystemCode.html">CoordinateSystemCode</a></dt>
    <dd><p>源坐标系</p>
</dd>
    <dt><code>to</code> <a class="xref" href="IFoxCAD.Cad.CoordinateSystemCode.html">CoordinateSystemCode</a></dt>
    <dd><p>目标坐标系</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Vector3d</span></dt>
    <dd><p>变换后的向量</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_Ucs2Wcs_" data-uid="IFoxCAD.Cad.GeometryEx.Ucs2Wcs*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Ucs2Wcs_Autodesk_AutoCAD_Geometry_Point3d_" data-uid="IFoxCAD.Cad.GeometryEx.Ucs2Wcs(Autodesk.AutoCAD.Geometry.Point3d)">
  Ucs2Wcs(Point3d)
  
  </h3>

  <div class="markdown level1 summary"><p>ucs到wcs的点变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point3d Ucs2Wcs(this Point3d point)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>point</code> <span class="xref">Point3d</span></dt>
    <dd><p>点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point3d</span></dt>
    <dd><p>变换后的点</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_Ucs2Wcs_" data-uid="IFoxCAD.Cad.GeometryEx.Ucs2Wcs*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Ucs2Wcs_Autodesk_AutoCAD_Geometry_Vector3d_" data-uid="IFoxCAD.Cad.GeometryEx.Ucs2Wcs(Autodesk.AutoCAD.Geometry.Vector3d)">
  Ucs2Wcs(Vector3d)
  
  </h3>

  <div class="markdown level1 summary"><p>ucs到wcs的向量变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Vector3d Ucs2Wcs(this Vector3d vec)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>vec</code> <span class="xref">Vector3d</span></dt>
    <dd><p>向量</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Vector3d</span></dt>
    <dd><p>变换后的向量</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_Wcs2Dcs_" data-uid="IFoxCAD.Cad.GeometryEx.Wcs2Dcs*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Wcs2Dcs_Autodesk_AutoCAD_Geometry_Point3d_System_Boolean_" data-uid="IFoxCAD.Cad.GeometryEx.Wcs2Dcs(Autodesk.AutoCAD.Geometry.Point3d,System.Boolean)">
  Wcs2Dcs(Point3d, bool)
  
  </h3>

  <div class="markdown level1 summary"><p>wcs到dcs的点变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point3d Wcs2Dcs(this Point3d point, bool atPaperSpace)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>point</code> <span class="xref">Point3d</span></dt>
    <dd><p>点</p>
</dd>
    <dt><code>atPaperSpace</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>是否为图纸空间</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point3d</span></dt>
    <dd><p>变换后的点</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_Wcs2Dcs_" data-uid="IFoxCAD.Cad.GeometryEx.Wcs2Dcs*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Wcs2Dcs_Autodesk_AutoCAD_Geometry_Vector3d_System_Boolean_" data-uid="IFoxCAD.Cad.GeometryEx.Wcs2Dcs(Autodesk.AutoCAD.Geometry.Vector3d,System.Boolean)">
  Wcs2Dcs(Vector3d, bool)
  
  </h3>

  <div class="markdown level1 summary"><p>wcs到dcs的向量变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Vector3d Wcs2Dcs(this Vector3d vec, bool atPaperSpace)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>vec</code> <span class="xref">Vector3d</span></dt>
    <dd><p>向量</p>
</dd>
    <dt><code>atPaperSpace</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>是否为图纸空间</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Vector3d</span></dt>
    <dd><p>变换后的向量</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_Wcs2Ucs_" data-uid="IFoxCAD.Cad.GeometryEx.Wcs2Ucs*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Wcs2Ucs_Autodesk_AutoCAD_Geometry_Point3d_" data-uid="IFoxCAD.Cad.GeometryEx.Wcs2Ucs(Autodesk.AutoCAD.Geometry.Point3d)">
  Wcs2Ucs(Point3d)
  
  </h3>

  <div class="markdown level1 summary"><p>wcs到ucs的点变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point3d Wcs2Ucs(this Point3d point)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>point</code> <span class="xref">Point3d</span></dt>
    <dd><p>点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point3d</span></dt>
    <dd><p>变换后的点</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_GeometryEx_Wcs2Ucs_" data-uid="IFoxCAD.Cad.GeometryEx.Wcs2Ucs*"></a>

  <h3 id="IFoxCAD_Cad_GeometryEx_Wcs2Ucs_Autodesk_AutoCAD_Geometry_Vector3d_" data-uid="IFoxCAD.Cad.GeometryEx.Wcs2Ucs(Autodesk.AutoCAD.Geometry.Vector3d)">
  Wcs2Ucs(Vector3d)
  
  </h3>

  <div class="markdown level1 summary"><p>wcs到ucs的向量变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Vector3d Wcs2Ucs(this Vector3d vec)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>vec</code> <span class="xref">Vector3d</span></dt>
    <dd><p>向量</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Vector3d</span></dt>
    <dd><p>变换后的向量</p>
</dd>
  </dl>












</article>

        <div class="contribution d-print-none">
        </div>

        
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>
  </body>
</html>