<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class CurveEx
 </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class CurveEx
 ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../public/docfx.min.css">
      <link rel="stylesheet" href="../public/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      <meta name="docfx:rel" content="../">
      
      
      
  </head>

  <script type="module">
    import options from './../public/main.js'
    import { init } from './../public/docfx.min.js'
    init(options)
  </script>

  <script>
    const theme = localStorage.getItem('theme') || 'auto'
    document.documentElement.setAttribute('data-bs-theme', theme === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : theme)
  </script>


  <body class="tex2jax_ignore" data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../logo.svg" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navpanel" aria-controls="navpanel" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navpanel">
            <div id="navbar">
              <form class="search" role="search" id="search">
                <i class="bi bi-search"></i>
                <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
              </form>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="IFoxCAD.Cad.CurveEx">



  <h1 id="IFoxCAD_Cad_CurveEx" data-uid="IFoxCAD.Cad.CurveEx" class="text-break">
    Class CurveEx
  
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><a class="xref" href="IFoxCAD.html">IFoxCAD</a>.<a class="xref" href="IFoxCAD.Cad.html">Cad</a></dd></dl>
  <dl><dt>Assembly</dt><dd>IFox.CAD.ACAD.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>实体类曲线扩展类</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static class CurveEx</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">CurveEx</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>






  <h2 class="section" id="methods">Methods
</h2>


  <a id="IFoxCAD_Cad_CurveEx_BreakCurve_" data-uid="IFoxCAD.Cad.CurveEx.BreakCurve*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_BreakCurve_System_Collections_Generic_List_Autodesk_AutoCAD_DatabaseServices_Curve__" data-uid="IFoxCAD.Cad.CurveEx.BreakCurve(System.Collections.Generic.List{Autodesk.AutoCAD.DatabaseServices.Curve})">
  BreakCurve(List&lt;Curve&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>曲线打断</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static List&lt;Curve&gt; BreakCurve(this List&lt;Curve&gt; curves)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curves</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>曲线列表</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>打断后的曲线列表</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_BreakCurveOnZPlane_" data-uid="IFoxCAD.Cad.CurveEx.BreakCurveOnZPlane*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_BreakCurveOnZPlane_System_Collections_Generic_List_Autodesk_AutoCAD_DatabaseServices_Curve__" data-uid="IFoxCAD.Cad.CurveEx.BreakCurveOnZPlane(System.Collections.Generic.List{Autodesk.AutoCAD.DatabaseServices.Curve})">
  BreakCurveOnZPlane(List&lt;Curve&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>在z法向量平面打断曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static List&lt;Curve&gt; BreakCurveOnZPlane(this List&lt;Curve&gt; curves)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curves</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>曲线列表</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>打断后的曲线列表</p>
</dd>
  </dl>








  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.argumentnullexception">ArgumentNullException</a></dt>
    <dd><p>传入的曲线列表错误</p>
</dd>
  </dl>



  <a id="IFoxCAD_Cad_CurveEx_ChamferAt_" data-uid="IFoxCAD.Cad.CurveEx.ChamferAt*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ChamferAt_Autodesk_AutoCAD_DatabaseServices_Polyline_System_Int32_System_Double_System_Boolean_" data-uid="IFoxCAD.Cad.CurveEx.ChamferAt(Autodesk.AutoCAD.DatabaseServices.Polyline,System.Int32,System.Double,System.Boolean)">
  ChamferAt(Polyline, int, double, bool)
  
  </h3>

  <div class="markdown level1 summary"><p>为优化多段线倒角</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static void ChamferAt(this Polyline polyline, int index, double radius, bool isFillet)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>polyline</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Polyline.html">Polyline</a></dt>
    <dd><p>优化多段线</p>
</dd>
    <dt><code>index</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd><p>顶点索引号</p>
</dd>
    <dt><code>radius</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>倒角半径</p>
</dd>
    <dt><code>isFillet</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>倒角类型</p>
</dd>
  </dl>












  <a id="IFoxCAD_Cad_CurveEx_GetAllCycle_" data-uid="IFoxCAD.Cad.CurveEx.GetAllCycle*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_GetAllCycle_System_Collections_Generic_IEnumerable_Autodesk_AutoCAD_DatabaseServices_Curve__" data-uid="IFoxCAD.Cad.CurveEx.GetAllCycle(System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.DatabaseServices.Curve})">
  GetAllCycle(IEnumerable&lt;Curve&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>获取曲线集所围成的封闭区域的曲线集，注意此函数不能处理平行边（两个点及两条线组成的闭合环）</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static IEnumerable&lt;Curve&gt; GetAllCycle(this IEnumerable&lt;Curve&gt; curves)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curves</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>曲线集合</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>所有的闭合环的曲线集合</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_GetLength_" data-uid="IFoxCAD.Cad.CurveEx.GetLength*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_GetLength_Autodesk_AutoCAD_DatabaseServices_Curve_" data-uid="IFoxCAD.Cad.CurveEx.GetLength(Autodesk.AutoCAD.DatabaseServices.Curve)">
  GetLength(Curve)
  
  </h3>

  <div class="markdown level1 summary"><p>曲线长度</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static double GetLength(this Curve curve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>曲线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>长度</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_GetScaleCurve_" data-uid="IFoxCAD.Cad.CurveEx.GetScaleCurve*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_GetScaleCurve_Autodesk_AutoCAD_DatabaseServices_Curve_Autodesk_AutoCAD_Geometry_Point3d_System_Double_System_Double_" data-uid="IFoxCAD.Cad.CurveEx.GetScaleCurve(Autodesk.AutoCAD.DatabaseServices.Curve,Autodesk.AutoCAD.Geometry.Point3d,System.Double,System.Double)">
  GetScaleCurve(Curve, Point3d, double, double)
  
  </h3>

  <div class="markdown level1 summary"><p>获取非等比转换的曲线（旋转投影法）</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Curve GetScaleCurve(this Curve cur, Point3d pt, double x, double y)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>cur</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>转换前的曲线</p>
</dd>
    <dt><code>pt</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd><p>基点</p>
</dd>
    <dt><code>x</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>x方向比例</p>
</dd>
    <dt><code>y</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>y方向比例</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>转换后的曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_GetSplitCurves_" data-uid="IFoxCAD.Cad.CurveEx.GetSplitCurves*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_GetSplitCurves_Autodesk_AutoCAD_DatabaseServices_Curve_System_Collections_Generic_IEnumerable_Autodesk_AutoCAD_Geometry_Point3d__" data-uid="IFoxCAD.Cad.CurveEx.GetSplitCurves(Autodesk.AutoCAD.DatabaseServices.Curve,System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.Geometry.Point3d})">
  GetSplitCurves(Curve, IEnumerable&lt;Point3d&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>获取分割曲线集合</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static IEnumerable&lt;Curve&gt; GetSplitCurves(this Curve curve, IEnumerable&lt;Point3d&gt; points)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>曲线</p>
</dd>
    <dt><code>points</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a>&gt;</dt>
    <dd><p>打断点表</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>打断后曲线的集合</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_GetSplitCurves_" data-uid="IFoxCAD.Cad.CurveEx.GetSplitCurves*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_GetSplitCurves_Autodesk_AutoCAD_DatabaseServices_Curve_System_Collections_Generic_IEnumerable_Autodesk_AutoCAD_Geometry_Point3d__System_Boolean_" data-uid="IFoxCAD.Cad.CurveEx.GetSplitCurves(Autodesk.AutoCAD.DatabaseServices.Curve,System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.Geometry.Point3d},System.Boolean)">
  GetSplitCurves(Curve, IEnumerable&lt;Point3d&gt;, bool)
  
  </h3>

  <div class="markdown level1 summary"><p>获取分割曲线集合</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static IEnumerable&lt;Curve&gt; GetSplitCurves(this Curve curve, IEnumerable&lt;Point3d&gt; points, bool isOrder = false)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>曲线</p>
</dd>
    <dt><code>points</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a>&gt;</dt>
    <dd><p>打断点表</p>
</dd>
    <dt><code>isOrder</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>对点表是否进行排序
<p>
<a href="https://learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/bool">true</a>按参数值升序排序<br>
<a href="https://learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/bool">false</a>不排序,默认值
</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>打断后曲线的集合</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_GetSplitCurves_" data-uid="IFoxCAD.Cad.CurveEx.GetSplitCurves*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_GetSplitCurves_Autodesk_AutoCAD_DatabaseServices_Curve_System_Collections_Generic_IEnumerable_System_Double__" data-uid="IFoxCAD.Cad.CurveEx.GetSplitCurves(Autodesk.AutoCAD.DatabaseServices.Curve,System.Collections.Generic.IEnumerable{System.Double})">
  GetSplitCurves(Curve, IEnumerable&lt;double&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>获取分割曲线集合</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static IEnumerable&lt;Curve&gt; GetSplitCurves(this Curve curve, IEnumerable&lt;double&gt; pars)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>曲线</p>
</dd>
    <dt><code>pars</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a>&gt;</dt>
    <dd><p>打断参数表</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>打断后曲线的集合</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_GetSplitCurves_" data-uid="IFoxCAD.Cad.CurveEx.GetSplitCurves*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_GetSplitCurves_Autodesk_AutoCAD_DatabaseServices_Curve_System_Collections_Generic_IEnumerable_System_Double__System_Boolean_" data-uid="IFoxCAD.Cad.CurveEx.GetSplitCurves(Autodesk.AutoCAD.DatabaseServices.Curve,System.Collections.Generic.IEnumerable{System.Double},System.Boolean)">
  GetSplitCurves(Curve, IEnumerable&lt;double&gt;, bool)
  
  </h3>

  <div class="markdown level1 summary"><p>获取分割曲线集合</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static IEnumerable&lt;Curve&gt; GetSplitCurves(this Curve curve, IEnumerable&lt;double&gt; pars, bool isOrder = false)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>曲线</p>
</dd>
    <dt><code>pars</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a>&gt;</dt>
    <dd><p>打断参数表</p>
</dd>
    <dt><code>isOrder</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>对参数表是否进行排序
<p>
<a href="https://learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/bool">true</a>按参数值升序排序<br>
<a href="https://learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/bool">false</a>不排序,默认值
</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a>&gt;</dt>
    <dd><p>打断后曲线的集合</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCompositeCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCompositeCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCompositeCurve3d_Autodesk_AutoCAD_DatabaseServices_Curve_" data-uid="IFoxCAD.Cad.CurveEx.ToCompositeCurve3d(Autodesk.AutoCAD.DatabaseServices.Curve)">
  ToCompositeCurve3d(Curve)
  
  </h3>

  <div class="markdown level1 summary"><p>将曲线转换为复合曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static CompositeCurve3d? ToCompositeCurve3d(this Curve curve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>曲线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.CompositeCurve3d.html">CompositeCurve3d</a></dt>
    <dd><p>复合曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCurve3d_Autodesk_AutoCAD_DatabaseServices_Arc_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d(Autodesk.AutoCAD.DatabaseServices.Arc)">
  ToCurve3d(Arc)
  
  </h3>

  <div class="markdown level1 summary"><p>将圆弧转换为ge圆弧曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static CircularArc3d ToCurve3d(this Arc arc)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>arc</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Arc.html">Arc</a></dt>
    <dd><p>圆弧</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.CircularArc3d.html">CircularArc3d</a></dt>
    <dd><p>ge圆弧曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCurve3d_Autodesk_AutoCAD_DatabaseServices_Circle_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d(Autodesk.AutoCAD.DatabaseServices.Circle)">
  ToCurve3d(Circle)
  
  </h3>

  <div class="markdown level1 summary"><p>将圆转换为ge圆弧曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static CircularArc3d ToCurve3d(this Circle cir)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>cir</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Circle.html">Circle</a></dt>
    <dd><p>圆</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.CircularArc3d.html">CircularArc3d</a></dt>
    <dd><p>ge圆弧曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCurve3d_Autodesk_AutoCAD_DatabaseServices_Curve_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d(Autodesk.AutoCAD.DatabaseServices.Curve)">
  ToCurve3d(Curve)
  
  </h3>

  <div class="markdown level1 summary"><p>将曲线转换为ge曲线，此函数将在未来淘汰，二惊加油</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Curve3d? ToCurve3d(this Curve curve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>曲线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html">Curve3d</a></dt>
    <dd><p>ge曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCurve3d_Autodesk_AutoCAD_DatabaseServices_Ellipse_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d(Autodesk.AutoCAD.DatabaseServices.Ellipse)">
  ToCurve3d(Ellipse)
  
  </h3>

  <div class="markdown level1 summary"><p>将椭圆转换为三维ge椭圆曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static EllipticalArc3d ToCurve3d(this Ellipse ell)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ell</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Ellipse.html">Ellipse</a></dt>
    <dd><p>椭圆</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.EllipticalArc3d.html">EllipticalArc3d</a></dt>
    <dd><p>三维ge椭圆曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCurve3d_Autodesk_AutoCAD_DatabaseServices_Line_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d(Autodesk.AutoCAD.DatabaseServices.Line)">
  ToCurve3d(Line)
  
  </h3>

  <div class="markdown level1 summary"><p>将直线转换为ge直线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static LineSegment3d ToCurve3d(this Line line)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>line</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Line.html">Line</a></dt>
    <dd><p>直线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.LineSegment3d.html">LineSegment3d</a></dt>
    <dd><p>ge直线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCurve3d_Autodesk_AutoCAD_DatabaseServices_Polyline_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d(Autodesk.AutoCAD.DatabaseServices.Polyline)">
  ToCurve3d(Polyline)
  
  </h3>

  <div class="markdown level1 summary"><p>多段线转换为复合曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static CompositeCurve3d ToCurve3d(this Polyline pl)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pl</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Polyline.html">Polyline</a></dt>
    <dd><p>多段线对象</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.CompositeCurve3d.html">CompositeCurve3d</a></dt>
    <dd><p>复合曲线对象</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCurve3d_Autodesk_AutoCAD_DatabaseServices_Polyline2d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d(Autodesk.AutoCAD.DatabaseServices.Polyline2d)">
  ToCurve3d(Polyline2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维多段线转换为三维ge曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Curve3d? ToCurve3d(this Polyline2d pl2d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pl2d</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Polyline2d.html">Polyline2d</a></dt>
    <dd><p>二维多段线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html">Curve3d</a></dt>
    <dd><p>三维ge曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCurve3d_Autodesk_AutoCAD_DatabaseServices_Polyline3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d(Autodesk.AutoCAD.DatabaseServices.Polyline3d)">
  ToCurve3d(Polyline3d)
  
  </h3>

  <div class="markdown level1 summary"><p>将三维多段线转换为三维曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Curve3d ToCurve3d(this Polyline3d pl3d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pl3d</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Polyline3d.html">Polyline3d</a></dt>
    <dd><p>三维多段线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html">Curve3d</a></dt>
    <dd><p>三维曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToCurve3d_Autodesk_AutoCAD_DatabaseServices_Spline_" data-uid="IFoxCAD.Cad.CurveEx.ToCurve3d(Autodesk.AutoCAD.DatabaseServices.Spline)">
  ToCurve3d(Spline)
  
  </h3>

  <div class="markdown level1 summary"><p>将样条曲线转换为三维Nurb曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static NurbCurve3d ToCurve3d(this Spline spl)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>spl</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Spline.html">Spline</a></dt>
    <dd><p>样条曲线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.NurbCurve3d.html">NurbCurve3d</a></dt>
    <dd><p>三维Nurb曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToEllipticalArc3d_" data-uid="IFoxCAD.Cad.CurveEx.ToEllipticalArc3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToEllipticalArc3d_Autodesk_AutoCAD_DatabaseServices_Arc_" data-uid="IFoxCAD.Cad.CurveEx.ToEllipticalArc3d(Autodesk.AutoCAD.DatabaseServices.Arc)">
  ToEllipticalArc3d(Arc)
  
  </h3>

  <div class="markdown level1 summary"><p>将圆弧转换为ge椭圆曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static EllipticalArc3d ToEllipticalArc3d(this Arc arc)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>arc</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Arc.html">Arc</a></dt>
    <dd><p>圆弧</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.EllipticalArc3d.html">EllipticalArc3d</a></dt>
    <dd><p>ge椭圆曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToEllipticalArc3d_" data-uid="IFoxCAD.Cad.CurveEx.ToEllipticalArc3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToEllipticalArc3d_Autodesk_AutoCAD_DatabaseServices_Circle_" data-uid="IFoxCAD.Cad.CurveEx.ToEllipticalArc3d(Autodesk.AutoCAD.DatabaseServices.Circle)">
  ToEllipticalArc3d(Circle)
  
  </h3>

  <div class="markdown level1 summary"><p>将圆转换为ge椭圆曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static EllipticalArc3d ToEllipticalArc3d(this Circle cir)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>cir</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Circle.html">Circle</a></dt>
    <dd><p>圆</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.EllipticalArc3d.html">EllipticalArc3d</a></dt>
    <dd><p>ge椭圆曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_Autodesk_AutoCAD_DatabaseServices_Arc_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d(Autodesk.AutoCAD.DatabaseServices.Arc)">
  ToNurbCurve3d(Arc)
  
  </h3>

  <div class="markdown level1 summary"><p>将圆弧转换为三维Nurb曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static NurbCurve3d ToNurbCurve3d(this Arc arc)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>arc</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Arc.html">Arc</a></dt>
    <dd><p>圆弧</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.NurbCurve3d.html">NurbCurve3d</a></dt>
    <dd><p>三维Nurb曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_Autodesk_AutoCAD_DatabaseServices_Circle_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d(Autodesk.AutoCAD.DatabaseServices.Circle)">
  ToNurbCurve3d(Circle)
  
  </h3>

  <div class="markdown level1 summary"><p>将圆转换为Nurb曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static NurbCurve3d ToNurbCurve3d(this Circle cir)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>cir</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Circle.html">Circle</a></dt>
    <dd><p>圆</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.NurbCurve3d.html">NurbCurve3d</a></dt>
    <dd><p>Nurb曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_Autodesk_AutoCAD_DatabaseServices_Curve_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d(Autodesk.AutoCAD.DatabaseServices.Curve)">
  ToNurbCurve3d(Curve)
  
  </h3>

  <div class="markdown level1 summary"><p>将曲线转换为Nurb曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static NurbCurve3d? ToNurbCurve3d(this Curve curve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Curve.html">Curve</a></dt>
    <dd><p>曲线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.NurbCurve3d.html">NurbCurve3d</a></dt>
    <dd><p>Nurb曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_Autodesk_AutoCAD_DatabaseServices_Ellipse_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d(Autodesk.AutoCAD.DatabaseServices.Ellipse)">
  ToNurbCurve3d(Ellipse)
  
  </h3>

  <div class="markdown level1 summary"><p>将椭圆转换为三维Nurb曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static NurbCurve3d ToNurbCurve3d(this Ellipse ell)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ell</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Ellipse.html">Ellipse</a></dt>
    <dd><p>椭圆</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.NurbCurve3d.html">NurbCurve3d</a></dt>
    <dd><p>三维Nurb曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_Autodesk_AutoCAD_DatabaseServices_Line_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d(Autodesk.AutoCAD.DatabaseServices.Line)">
  ToNurbCurve3d(Line)
  
  </h3>

  <div class="markdown level1 summary"><p>将直线转换为Nurb曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static NurbCurve3d ToNurbCurve3d(this Line line)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>line</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Line.html">Line</a></dt>
    <dd><p>直线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.NurbCurve3d.html">NurbCurve3d</a></dt>
    <dd><p>Nurb曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_Autodesk_AutoCAD_DatabaseServices_Polyline_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d(Autodesk.AutoCAD.DatabaseServices.Polyline)">
  ToNurbCurve3d(Polyline)
  
  </h3>

  <div class="markdown level1 summary"><p>多段线转换为Nurb曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static NurbCurve3d? ToNurbCurve3d(this Polyline pl)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pl</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Polyline.html">Polyline</a></dt>
    <dd><p>多段线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.NurbCurve3d.html">NurbCurve3d</a></dt>
    <dd><p>Nurb曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_Autodesk_AutoCAD_DatabaseServices_Polyline2d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d(Autodesk.AutoCAD.DatabaseServices.Polyline2d)">
  ToNurbCurve3d(Polyline2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维多段线转换为三维Nurb曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static NurbCurve3d? ToNurbCurve3d(this Polyline2d pl2d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pl2d</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Polyline2d.html">Polyline2d</a></dt>
    <dd><p>二维多段线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.NurbCurve3d.html">NurbCurve3d</a></dt>
    <dd><p>三维Nurb曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToNurbCurve3d_Autodesk_AutoCAD_DatabaseServices_Polyline3d_" data-uid="IFoxCAD.Cad.CurveEx.ToNurbCurve3d(Autodesk.AutoCAD.DatabaseServices.Polyline3d)">
  ToNurbCurve3d(Polyline3d)
  
  </h3>

  <div class="markdown level1 summary"><p>将三维多段线转换为三维Nurb曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static NurbCurve3d ToNurbCurve3d(this Polyline3d pl3d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pl3d</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Polyline3d.html">Polyline3d</a></dt>
    <dd><p>三维多段线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.NurbCurve3d.html">NurbCurve3d</a></dt>
    <dd><p>三维Nurb曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToPolylineCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToPolylineCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToPolylineCurve3d_Autodesk_AutoCAD_DatabaseServices_Polyline2d_" data-uid="IFoxCAD.Cad.CurveEx.ToPolylineCurve3d(Autodesk.AutoCAD.DatabaseServices.Polyline2d)">
  ToPolylineCurve3d(Polyline2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维多段线转换为三维ge多段线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static PolylineCurve3d ToPolylineCurve3d(this Polyline2d pl)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pl</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Polyline2d.html">Polyline2d</a></dt>
    <dd><p>二维多段线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.PolylineCurve3d.html">PolylineCurve3d</a></dt>
    <dd><p>三维ge多段线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_CurveEx_ToPolylineCurve3d_" data-uid="IFoxCAD.Cad.CurveEx.ToPolylineCurve3d*"></a>

  <h3 id="IFoxCAD_Cad_CurveEx_ToPolylineCurve3d_Autodesk_AutoCAD_DatabaseServices_Polyline3d_" data-uid="IFoxCAD.Cad.CurveEx.ToPolylineCurve3d(Autodesk.AutoCAD.DatabaseServices.Polyline3d)">
  ToPolylineCurve3d(Polyline3d)
  
  </h3>

  <div class="markdown level1 summary"><p>将三维多段线转换为三维ge多段线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static PolylineCurve3d ToPolylineCurve3d(this Polyline3d pl)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pl</code> <a class="xref" href="Autodesk.AutoCAD.DatabaseServices.Polyline3d.html">Polyline3d</a></dt>
    <dd><p>三维多段线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.PolylineCurve3d.html">PolylineCurve3d</a></dt>
    <dd><p>三维ge多段线</p>
</dd>
  </dl>












</article>

        <div class="contribution d-print-none">
        </div>

        
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>

    <div class="container-xxl search-results" id="search-results"></div>

    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>
  </body>
</html>