<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class PointEx
 </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class PointEx
 ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../public/docfx.min.css">
      <link rel="stylesheet" href="../public/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      
      
      
  </head>

  <script type="module">
    import options from './../public/main.js'
    import { init } from './../public/docfx.min.js'
    init(options)
  </script>

  <script>
    const theme = localStorage.getItem('theme') || 'auto'
    document.documentElement.setAttribute('data-bs-theme', theme === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : theme)
  </script>


  <body class="tex2jax_ignore" data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../logo.svg" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navpanel" aria-controls="navpanel" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navpanel">
            <div id="navbar">
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="IFoxCAD.Cad.PointEx">



  <h1 id="IFoxCAD_Cad_PointEx" data-uid="IFoxCAD.Cad.PointEx" class="text-break">
    Class PointEx
  
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><a class="xref" href="IFoxCAD.html">IFoxCAD</a>.<a class="xref" href="IFoxCAD.Cad.html">Cad</a></dd></dl>
  <dl><dt>Assembly</dt><dd>IFox.CAD.ACAD.dll</dd></dl>
  </div>

  <div class="markdown summary"></div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static class PointEx</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">PointEx</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>






  <h2 class="section" id="methods">Methods
</h2>


  <a id="IFoxCAD_Cad_PointEx_End2End_" data-uid="IFoxCAD.Cad.PointEx.End2End*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_End2End_Autodesk_AutoCAD_Geometry_Point2dCollection_" data-uid="IFoxCAD.Cad.PointEx.End2End(Autodesk.AutoCAD.Geometry.Point2dCollection)">
  End2End(Point2dCollection)
  
  </h3>

  <div class="markdown level1 summary"><p>首尾相连</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static void End2End(this Point2dCollection ptcol)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ptcol</code> <span class="xref">Point2dCollection</span></dt>
    <dd></dd>
  </dl>












  <a id="IFoxCAD_Cad_PointEx_End2End_" data-uid="IFoxCAD.Cad.PointEx.End2End*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_End2End_Autodesk_AutoCAD_Geometry_Point3dCollection_" data-uid="IFoxCAD.Cad.PointEx.End2End(Autodesk.AutoCAD.Geometry.Point3dCollection)">
  End2End(Point3dCollection)
  
  </h3>

  <div class="markdown level1 summary"><p>首尾相连</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static void End2End(this Point3dCollection ptcol)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ptcol</code> <span class="xref">Point3dCollection</span></dt>
    <dd></dd>
  </dl>












  <a id="IFoxCAD_Cad_PointEx_GetAngle_" data-uid="IFoxCAD.Cad.PointEx.GetAngle*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_GetAngle_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_" data-uid="IFoxCAD.Cad.PointEx.GetAngle(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d)">
  GetAngle(Point2d, Point2d)
  
  </h3>

  <div class="markdown level1 summary"><p>两点计算弧度范围0到2Pi</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static double GetAngle(this Point2d startPoint, Point2d endPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>startPoint</code> <span class="xref">Point2d</span></dt>
    <dd><p>起点</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point2d</span></dt>
    <dd><p>终点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>弧度值</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_PointEx_GetAngle_" data-uid="IFoxCAD.Cad.PointEx.GetAngle*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_GetAngle_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Point3d_System_Nullable_Autodesk_AutoCAD_Geometry_Vector3d__" data-uid="IFoxCAD.Cad.PointEx.GetAngle(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,System.Nullable{Autodesk.AutoCAD.Geometry.Vector3d})">
  GetAngle(Point3d, Point3d, Vector3d?)
  
  </h3>

  <div class="markdown level1 summary"><p>两点计算弧度范围0到2Pi</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static double GetAngle(this Point3d startPoint, Point3d endPoint, Vector3d? direction = null)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>startPoint</code> <span class="xref">Point3d</span></dt>
    <dd><p>起点</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point3d</span></dt>
    <dd><p>终点</p>
</dd>
    <dt><code>direction</code> <span class="xref">Vector3d</span>?</dt>
    <dd><p>方向</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>弧度值</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_PointEx_GetArcBulge_" data-uid="IFoxCAD.Cad.PointEx.GetArcBulge*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_GetArcBulge_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_System_Double_" data-uid="IFoxCAD.Cad.PointEx.GetArcBulge(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,System.Double)">
  GetArcBulge(Point2d, Point2d, Point2d, double)
  
  </h3>

  <div class="markdown level1 summary"><p>求凸度,判断三点是否一条直线上</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static double GetArcBulge(this Point2d arc1, Point2d arc2, Point2d arc3, double tol = 1E-10)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>arc1</code> <span class="xref">Point2d</span></dt>
    <dd><p>圆弧起点</p>
</dd>
    <dt><code>arc2</code> <span class="xref">Point2d</span></dt>
    <dd><p>圆弧腰点</p>
</dd>
    <dt><code>arc3</code> <span class="xref">Point2d</span></dt>
    <dd><p>圆弧尾点</p>
</dd>
    <dt><code>tol</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>容差</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>逆时针为正,顺时针为负</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_PointEx_GetHashString_" data-uid="IFoxCAD.Cad.PointEx.GetHashString*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_GetHashString_Autodesk_AutoCAD_Geometry_Point3d_System_Int32_System_Int32_" data-uid="IFoxCAD.Cad.PointEx.GetHashString(Autodesk.AutoCAD.Geometry.Point3d,System.Int32,System.Int32)">
  GetHashString(Point3d, int, int)
  
  </h3>

  <div class="markdown level1 summary"><p>获取点的hash字符串，同时可以作为pt的字符串表示</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static string GetHashString(this Point3d pt, int xyz = 3, int decimalRetain = 6)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pt</code> <span class="xref">Point3d</span></dt>
    <dd><p>点</p>
</dd>
    <dt><code>xyz</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd><p>指示计算几维坐标的标志，1为计算x，2为计算x，y，其他为计算x，y，z</p>
</dd>
    <dt><code>decimalRetain</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd><p>保留的小数位数</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.string">string</a></dt>
    <dd><p>hash字符串</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_PointEx_GetMidPointTo_" data-uid="IFoxCAD.Cad.PointEx.GetMidPointTo*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_GetMidPointTo_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Point2d_" data-uid="IFoxCAD.Cad.PointEx.GetMidPointTo(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d)">
  GetMidPointTo(Point2d, Point2d)
  
  </h3>

  <div class="markdown level1 summary"><p>获取中点</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point2d GetMidPointTo(this Point2d a, Point2d b)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>a</code> <span class="xref">Point2d</span></dt>
    <dd></dd>
    <dt><code>b</code> <span class="xref">Point2d</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point2d</span></dt>
    <dd></dd>
  </dl>











  <a id="IFoxCAD_Cad_PointEx_GetMidPointTo_" data-uid="IFoxCAD.Cad.PointEx.GetMidPointTo*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_GetMidPointTo_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Point3d_" data-uid="IFoxCAD.Cad.PointEx.GetMidPointTo(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
  GetMidPointTo(Point3d, Point3d)
  
  </h3>

  <div class="markdown level1 summary"><p>获取两个点之间的中点</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point3d GetMidPointTo(this Point3d pt1, Point3d pt2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pt1</code> <span class="xref">Point3d</span></dt>
    <dd><p>第一点</p>
</dd>
    <dt><code>pt2</code> <span class="xref">Point3d</span></dt>
    <dd><p>第二点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point3d</span></dt>
    <dd><p>返回两个点之间的中点</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_PointEx_Point2d_" data-uid="IFoxCAD.Cad.PointEx.Point2d*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_Point2d_Autodesk_AutoCAD_Geometry_Point3d_" data-uid="IFoxCAD.Cad.PointEx.Point2d(Autodesk.AutoCAD.Geometry.Point3d)">
  Point2d(Point3d)
  
  </h3>

  <div class="markdown level1 summary"><p>将三维点转换为二维点</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point2d Point2d(this Point3d pt)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pt</code> <span class="xref">Point3d</span></dt>
    <dd><p>三维点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point2d</span></dt>
    <dd><p>二维点</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_PointEx_Point2d_" data-uid="IFoxCAD.Cad.PointEx.Point2d*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_Point2d_System_Collections_Generic_IEnumerable_Autodesk_AutoCAD_Geometry_Point3d__" data-uid="IFoxCAD.Cad.PointEx.Point2d(System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.Geometry.Point3d})">
  Point2d(IEnumerable&lt;Point3d&gt;)
  
  </h3>

  <div class="markdown level1 summary"><p>将三维点集转换为二维点集</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static IEnumerable&lt;Point2d&gt; Point2d(this IEnumerable&lt;Point3d&gt; pts)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pts</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Point3d</span>&gt;</dt>
    <dd><p>三维点集</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Point2d</span>&gt;</dt>
    <dd><p>二维点集</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_PointEx_Point3d_" data-uid="IFoxCAD.Cad.PointEx.Point3d*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_Point3d_Autodesk_AutoCAD_Geometry_Point2d_System_Double_" data-uid="IFoxCAD.Cad.PointEx.Point3d(Autodesk.AutoCAD.Geometry.Point2d,System.Double)">
  Point3d(Point2d, double)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维点转换为三维点</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point3d Point3d(this Point2d pt, double z = 0)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pt</code> <span class="xref">Point2d</span></dt>
    <dd><p>二维点</p>
</dd>
    <dt><code>z</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>Z值</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point3d</span></dt>
    <dd><p>三维点</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_PointEx_Polar_" data-uid="IFoxCAD.Cad.PointEx.Polar*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_Polar_Autodesk_AutoCAD_Geometry_Point2d_System_Double_System_Double_" data-uid="IFoxCAD.Cad.PointEx.Polar(Autodesk.AutoCAD.Geometry.Point2d,System.Double,System.Double)">
  Polar(Point2d, double, double)
  
  </h3>

  <div class="markdown level1 summary"><p>计算指定距离和角度的点</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point2d Polar(this Point2d pt, double ang, double len)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pt</code> <span class="xref">Point2d</span></dt>
    <dd><p>基点</p>
</dd>
    <dt><code>ang</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>角度，x轴正向逆时针弧度</p>
</dd>
    <dt><code>len</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>距离</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point2d</span></dt>
    <dd><p>目标点</p>
</dd>
  </dl>







  <h4 class="section" id="IFoxCAD_Cad_PointEx_Polar_Autodesk_AutoCAD_Geometry_Point2d_System_Double_System_Double__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>本函数仅适用于x-y平面</p>
</div>




  <a id="IFoxCAD_Cad_PointEx_Polar_" data-uid="IFoxCAD.Cad.PointEx.Polar*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_Polar_Autodesk_AutoCAD_Geometry_Point3d_System_Double_System_Double_" data-uid="IFoxCAD.Cad.PointEx.Polar(Autodesk.AutoCAD.Geometry.Point3d,System.Double,System.Double)">
  Polar(Point3d, double, double)
  
  </h3>

  <div class="markdown level1 summary"><p>计算指定距离和角度的点</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point3d Polar(this Point3d pt, double ang, double len)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pt</code> <span class="xref">Point3d</span></dt>
    <dd><p>基点</p>
</dd>
    <dt><code>ang</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>角度，x轴正向逆时针弧度</p>
</dd>
    <dt><code>len</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>距离</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point3d</span></dt>
    <dd><p>目标点</p>
</dd>
  </dl>







  <h4 class="section" id="IFoxCAD_Cad_PointEx_Polar_Autodesk_AutoCAD_Geometry_Point3d_System_Double_System_Double__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>本函数仅适用于x-y平面</p>
</div>




  <a id="IFoxCAD_Cad_PointEx_TransPoint_" data-uid="IFoxCAD.Cad.PointEx.TransPoint*"></a>

  <h3 id="IFoxCAD_Cad_PointEx_TransPoint_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Point3d_System_Double_" data-uid="IFoxCAD.Cad.PointEx.TransPoint(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,System.Double)">
  TransPoint(Point3d, Point3d, Point3d, double)
  
  </h3>

  <div class="markdown level1 summary"><p>根据世界坐标计算用户坐标</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point3d TransPoint(this Point3d basePt, Point3d userPt, Point3d transPt, double ang)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>basePt</code> <span class="xref">Point3d</span></dt>
    <dd><p>基点世界坐标</p>
</dd>
    <dt><code>userPt</code> <span class="xref">Point3d</span></dt>
    <dd><p>基点用户坐标</p>
</dd>
    <dt><code>transPt</code> <span class="xref">Point3d</span></dt>
    <dd><p>目标世界坐标</p>
</dd>
    <dt><code>ang</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>坐标网旋转角，按x轴正向逆时针弧度</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point3d</span></dt>
    <dd><p>目标用户坐标</p>
</dd>
  </dl>












</article>

        <div class="contribution d-print-none">
        </div>

        
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>
  </body>
</html>