<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class LineSegment3d
 </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class LineSegment3d
 ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../public/docfx.min.css">
      <link rel="stylesheet" href="../public/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      <meta name="docfx:rel" content="../">
      
      
      
  </head>

  <script type="module">
    import options from './../public/main.js'
    import { init } from './../public/docfx.min.js'
    init(options)
  </script>

  <script>
    const theme = localStorage.getItem('theme') || 'auto'
    document.documentElement.setAttribute('data-bs-theme', theme === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : theme)
  </script>


  <body class="tex2jax_ignore" data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../logo.svg" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navpanel" aria-controls="navpanel" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navpanel">
            <div id="navbar">
              <form class="search" role="search" id="search">
                <i class="bi bi-search"></i>
                <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
              </form>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d">



  <h1 id="Autodesk_AutoCAD_Geometry_LineSegment3d" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d" class="text-break">
    Class LineSegment3d
  
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><a class="xref" href="Autodesk.html">Autodesk</a>.<a class="xref" href="Autodesk.AutoCAD.html">AutoCAD</a>.<a class="xref" href="Autodesk.AutoCAD.Geometry.html">Geometry</a></dd></dl>
  <dl><dt>Assembly</dt><dd>Acdbmgd.dll</dd></dl>
  </div>

  <div class="markdown summary"></div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[Wrapper(&quot;AcGeLineSeg3d&quot;)]
public sealed class LineSegment3d : LinearEntity3d, IDisposable, ICloneable</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.marshalbyrefobject">MarshalByRefObject</a></div>
      <div><a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html">DisposableWrapper</a></div>
      <div><a class="xref" href="Autodesk.AutoCAD.Geometry.Entity3d.html">Entity3d</a></div>
      <div><a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html">Curve3d</a></div>
      <div><a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html">LinearEntity3d</a></div>
      <div><span class="xref">LineSegment3d</span></div>
    </dd>
  </dl>

  <dl class="typelist implements">
    <dt>Implements</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.idisposable">IDisposable</a></div>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.icloneable">ICloneable</a></div>
    </dd>
  </dl>


  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IntersectWith_Autodesk_AutoCAD_Geometry_PlanarEntity_">LinearEntity3d.IntersectWith(PlanarEntity)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IntersectWith_Autodesk_AutoCAD_Geometry_PlanarEntity_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.IntersectWith(PlanarEntity, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IntersectWith_Autodesk_AutoCAD_Geometry_LinearEntity3d_">LinearEntity3d.IntersectWith(LinearEntity3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IntersectWith_Autodesk_AutoCAD_Geometry_LinearEntity3d_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.IntersectWith(LinearEntity3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_ProjectedIntersectWith_Autodesk_AutoCAD_Geometry_LinearEntity3d_Autodesk_AutoCAD_Geometry_Vector3d_">LinearEntity3d.ProjectedIntersectWith(LinearEntity3d, Vector3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_ProjectedIntersectWith_Autodesk_AutoCAD_Geometry_LinearEntity3d_Autodesk_AutoCAD_Geometry_Vector3d_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.ProjectedIntersectWith(LinearEntity3d, Vector3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_Overlap_Autodesk_AutoCAD_Geometry_LinearEntity3d_">LinearEntity3d.Overlap(LinearEntity3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_Overlap_Autodesk_AutoCAD_Geometry_LinearEntity3d_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.Overlap(LinearEntity3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsOn_Autodesk_AutoCAD_Geometry_Plane_">LinearEntity3d.IsOn(Plane)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsOn_Autodesk_AutoCAD_Geometry_Plane_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.IsOn(Plane, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsParallelTo_Autodesk_AutoCAD_Geometry_PlanarEntity_">LinearEntity3d.IsParallelTo(PlanarEntity)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsParallelTo_Autodesk_AutoCAD_Geometry_PlanarEntity_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.IsParallelTo(PlanarEntity, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsParallelTo_Autodesk_AutoCAD_Geometry_LinearEntity3d_">LinearEntity3d.IsParallelTo(LinearEntity3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsParallelTo_Autodesk_AutoCAD_Geometry_LinearEntity3d_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.IsParallelTo(LinearEntity3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsPerpendicularTo_Autodesk_AutoCAD_Geometry_PlanarEntity_">LinearEntity3d.IsPerpendicularTo(PlanarEntity)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsPerpendicularTo_Autodesk_AutoCAD_Geometry_PlanarEntity_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.IsPerpendicularTo(PlanarEntity, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsPerpendicularTo_Autodesk_AutoCAD_Geometry_LinearEntity3d_">LinearEntity3d.IsPerpendicularTo(LinearEntity3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsPerpendicularTo_Autodesk_AutoCAD_Geometry_LinearEntity3d_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.IsPerpendicularTo(LinearEntity3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsColinearTo_Autodesk_AutoCAD_Geometry_LinearEntity3d_">LinearEntity3d.IsColinearTo(LinearEntity3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_IsColinearTo_Autodesk_AutoCAD_Geometry_LinearEntity3d_Autodesk_AutoCAD_Geometry_Tolerance_">LinearEntity3d.IsColinearTo(LinearEntity3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_GetPerpendicularPlane_Autodesk_AutoCAD_Geometry_Point3d_">LinearEntity3d.GetPerpendicularPlane(Point3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_GetLine">LinearEntity3d.GetLine()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_Direction">LinearEntity3d.Direction</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.LinearEntity3d.html#Autodesk_AutoCAD_Geometry_LinearEntity3d_PointOnLine">LinearEntity3d.PointOnLine</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetInterval">Curve3d.GetInterval()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_SetInterval_Autodesk_AutoCAD_Geometry_Interval_">Curve3d.SetInterval(Interval)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetReverseParameterCurve">Curve3d.GetReverseParameterCurve()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetDistanceTo_Autodesk_AutoCAD_Geometry_Curve3d_">Curve3d.GetDistanceTo(Curve3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetDistanceTo_Autodesk_AutoCAD_Geometry_Curve3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetDistanceTo(Curve3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetDistanceTo_Autodesk_AutoCAD_Geometry_Point3d_">Curve3d.GetDistanceTo(Point3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetDistanceTo_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetDistanceTo(Point3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetClosestPointTo_Autodesk_AutoCAD_Geometry_Curve3d_">Curve3d.GetClosestPointTo(Curve3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetClosestPointTo_Autodesk_AutoCAD_Geometry_Curve3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetClosestPointTo(Curve3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetClosestPointTo_Autodesk_AutoCAD_Geometry_Point3d_">Curve3d.GetClosestPointTo(Point3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetClosestPointTo_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetClosestPointTo(Point3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetProjectedClosestPointTo_Autodesk_AutoCAD_Geometry_Curve3d_Autodesk_AutoCAD_Geometry_Vector3d_">Curve3d.GetProjectedClosestPointTo(Curve3d, Vector3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetProjectedClosestPointTo_Autodesk_AutoCAD_Geometry_Curve3d_Autodesk_AutoCAD_Geometry_Vector3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetProjectedClosestPointTo(Curve3d, Vector3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetProjectedClosestPointTo_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Vector3d_">Curve3d.GetProjectedClosestPointTo(Point3d, Vector3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetProjectedClosestPointTo_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Vector3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetProjectedClosestPointTo(Point3d, Vector3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetNormalPoint_Autodesk_AutoCAD_Geometry_Point3d_">Curve3d.GetNormalPoint(Point3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetNormalPoint_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetNormalPoint(Point3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetBoundBlockOf_Autodesk_AutoCAD_Geometry_Interval_">Curve3d.GetBoundBlockOf(Interval)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetOrthoBoundBlockOf_Autodesk_AutoCAD_Geometry_Interval_">Curve3d.GetOrthoBoundBlockOf(Interval)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetProjectedEntity_Autodesk_AutoCAD_Geometry_Plane_Autodesk_AutoCAD_Geometry_Vector3d_">Curve3d.GetProjectedEntity(Plane, Vector3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetProjectedEntity_Autodesk_AutoCAD_Geometry_Plane_Autodesk_AutoCAD_Geometry_Vector3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetProjectedEntity(Plane, Vector3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetOrthoProjectEntity_Autodesk_AutoCAD_Geometry_Plane_">Curve3d.GetOrthoProjectEntity(Plane)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetOrthoProjectEntity_Autodesk_AutoCAD_Geometry_Plane_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetOrthoProjectEntity(Plane, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsOn_System_Double_">Curve3d.IsOn(double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsOn_System_Double_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.IsOn(double, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsOn_Autodesk_AutoCAD_Geometry_Point3d_System_Double__">Curve3d.IsOn(Point3d, out double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsOn_Autodesk_AutoCAD_Geometry_Point3d_System_Double__Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.IsOn(Point3d, out double, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsOn_Autodesk_AutoCAD_Geometry_Point3d_">Curve3d.IsOn(Point3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsOn_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.IsOn(Point3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetParameterOf_Autodesk_AutoCAD_Geometry_Point3d_">Curve3d.GetParameterOf(Point3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetParameterOf_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetParameterOf(Point3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetTrimmedOffset_System_Double_Autodesk_AutoCAD_Geometry_Vector3d_Autodesk_AutoCAD_Geometry_OffsetCurveExtensionType_">Curve3d.GetTrimmedOffset(double, Vector3d, OffsetCurveExtensionType)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetTrimmedOffset_System_Double_Autodesk_AutoCAD_Geometry_Vector3d_Autodesk_AutoCAD_Geometry_OffsetCurveExtensionType_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetTrimmedOffset(double, Vector3d, OffsetCurveExtensionType, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsClosed">Curve3d.IsClosed()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsClosed_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.IsClosed(Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsPlanar_Autodesk_AutoCAD_Geometry_Plane__">Curve3d.IsPlanar(out Plane)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsPlanar_Autodesk_AutoCAD_Geometry_Plane__Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.IsPlanar(out Plane, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsLinear_Autodesk_AutoCAD_Geometry_Line3d__">Curve3d.IsLinear(out Line3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsLinear_Autodesk_AutoCAD_Geometry_Line3d__Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.IsLinear(out Line3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsCoplanarWith_Autodesk_AutoCAD_Geometry_Curve3d_Autodesk_AutoCAD_Geometry_Plane__">Curve3d.IsCoplanarWith(Curve3d, out Plane)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsCoplanarWith_Autodesk_AutoCAD_Geometry_Curve3d_Autodesk_AutoCAD_Geometry_Plane__Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.IsCoplanarWith(Curve3d, out Plane, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsPeriodic_System_Double__">Curve3d.IsPeriodic(out double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsDegenerate_Autodesk_AutoCAD_Geometry_Entity3d__">Curve3d.IsDegenerate(out Entity3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_IsDegenerate_Autodesk_AutoCAD_Geometry_Entity3d__Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.IsDegenerate(out Entity3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetLength_System_Double_System_Double_System_Double_">Curve3d.GetLength(double, double, double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetParameterAtLength_System_Double_System_Double_System_Boolean_System_Double_">Curve3d.GetParameterAtLength(double, double, bool, double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetArea_System_Double_System_Double_">Curve3d.GetArea(double, double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetArea_System_Double_System_Double_Autodesk_AutoCAD_Geometry_Tolerance_">Curve3d.GetArea(double, double, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetSplitCurves_System_Double_">Curve3d.GetSplitCurves(double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_Explode_Autodesk_AutoCAD_Geometry_Interval_">Curve3d.Explode(Interval)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_EvaluatePoint_System_Double_">Curve3d.EvaluatePoint(double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetSamplePoints_System_Int32_">Curve3d.GetSamplePoints(int)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetSamplePoints_System_Double_System_Double_System_Double_">Curve3d.GetSamplePoints(double, double, double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_GetNewSamplePoints_System_Double_System_Double_System_Double_">Curve3d.GetNewSamplePoints(double, double, double)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_HasEndPoint">Curve3d.HasEndPoint</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_HasStartPoint">Curve3d.HasStartPoint</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_OrthoBoundBlock">Curve3d.OrthoBoundBlock</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html#Autodesk_AutoCAD_Geometry_Curve3d_BoundBlock">Curve3d.BoundBlock</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity3d.html#Autodesk_AutoCAD_Geometry_Entity3d_Clone">Entity3d.Clone()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity3d.html#Autodesk_AutoCAD_Geometry_Entity3d_IsEqualTo_Autodesk_AutoCAD_Geometry_Entity3d_">Entity3d.IsEqualTo(Entity3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity3d.html#Autodesk_AutoCAD_Geometry_Entity3d_IsEqualTo_Autodesk_AutoCAD_Geometry_Entity3d_Autodesk_AutoCAD_Geometry_Tolerance_">Entity3d.IsEqualTo(Entity3d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity3d.html#Autodesk_AutoCAD_Geometry_Entity3d_TransformBy_Autodesk_AutoCAD_Geometry_Matrix3d_">Entity3d.TransformBy(Matrix3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity3d.html#Autodesk_AutoCAD_Geometry_Entity3d_TranslateBy_Autodesk_AutoCAD_Geometry_Vector3d_">Entity3d.TranslateBy(Vector3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity3d.html#Autodesk_AutoCAD_Geometry_Entity3d_RotateBy_System_Double_Autodesk_AutoCAD_Geometry_Vector3d_Autodesk_AutoCAD_Geometry_Point3d_">Entity3d.RotateBy(double, Vector3d, Point3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity3d.html#Autodesk_AutoCAD_Geometry_Entity3d_Mirror_Autodesk_AutoCAD_Geometry_Plane_">Entity3d.Mirror(Plane)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity3d.html#Autodesk_AutoCAD_Geometry_Entity3d_ScaleBy_System_Double_Autodesk_AutoCAD_Geometry_Point3d_">Entity3d.ScaleBy(double, Point3d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_Create_System_Type_System_IntPtr_System_Boolean_">DisposableWrapper.Create(Type, IntPtr, bool)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_Equals_System_Object_">DisposableWrapper.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_GetHashCode">DisposableWrapper.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_Dispose">DisposableWrapper.Dispose()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_AutoDelete">DisposableWrapper.AutoDelete</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_IsDisposed">DisposableWrapper.IsDisposed</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_UnmanagedObject">DisposableWrapper.UnmanagedObject</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.marshalbyrefobject.getlifetimeservice">MarshalByRefObject.GetLifetimeService()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.marshalbyrefobject.initializelifetimeservice">MarshalByRefObject.InitializeLifetimeService()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.marshalbyrefobject.createobjref">MarshalByRefObject.CreateObjRef(Type)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype">object.GetType()</a>
    </div>
  </dd></dl>

  <dl class="typelist extensionMethods">
    <dt>Extension Methods</dt>
    <dd>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD.Basal.ArgumentNullEx.NotNull``1(``0,System.String)">ArgumentNullEx.NotNull&lt;T&gt;(T, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD.Basal.ArgumentNullEx.NotNull``1(``0,System.String)">ArgumentNullEx.NotNull&lt;T&gt;(T, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD.Basal.ArgumentNullEx.NotNull``1(``0,System.String)">ArgumentNullEx.NotNull&lt;T&gt;(T, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD_Basal_ArgumentNullEx_NotNull_System_Object_System_String_">ArgumentNullEx.NotNull(object?, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD_Basal_ArgumentNullEx_NotNull_System_Object_System_String_">ArgumentNullEx.NotNull(object?, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD_Basal_ArgumentNullEx_NotNull_System_Object_System_String_">ArgumentNullEx.NotNull(object?, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_GetProperty_System_Object_System_String_System_Object___">LateBinding.GetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_GetProperty_System_Object_System_String_System_Object___">LateBinding.GetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_GetProperty_System_Object_System_String_System_Object___">LateBinding.GetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_Invoke_System_Object_System_String_System_Object___">LateBinding.Invoke(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_Invoke_System_Object_System_String_System_Object___">LateBinding.Invoke(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_Invoke_System_Object_System_String_System_Object___">LateBinding.Invoke(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_ReleaseInstance_System_Object_">LateBinding.ReleaseInstance(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_ReleaseInstance_System_Object_">LateBinding.ReleaseInstance(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_ReleaseInstance_System_Object_">LateBinding.ReleaseInstance(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_SetProperty_System_Object_System_String_System_Object___">LateBinding.SetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_SetProperty_System_Object_System_String_System_Object___">LateBinding.SetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_SetProperty_System_Object_System_String_System_Object___">LateBinding.SetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_PrintLine_System_Object_">ObjEx.PrintLine(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_PrintLine_System_Object_">ObjEx.PrintLine(object)</a>
  </div>
  </dd></dl>





  <h2 class="section" id="constructors">Constructors
</h2>


  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d__ctor_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.#ctor*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d__ctor" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.#ctor">
  LineSegment3d()
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public LineSegment3d()</code></pre>
  </div>













  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d__ctor_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.#ctor*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d__ctor_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Point3d_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.#ctor(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
  LineSegment3d(Point3d, Point3d)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public LineSegment3d(Point3d point1, Point3d point2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>point1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
    <dt><code>point2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d__ctor_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.#ctor*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d__ctor_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Vector3d_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.#ctor(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Vector3d)">
  LineSegment3d(Point3d, Vector3d)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public LineSegment3d(Point3d point, Vector3d vector)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>point</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
    <dt><code>vector</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Vector3d.html">Vector3d</a></dt>
    <dd></dd>
  </dl>












  <h2 class="section" id="properties">Properties
</h2>


  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_EndPoint_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.EndPoint*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_EndPoint" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.EndPoint">
  EndPoint
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Point3d EndPoint { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
  </dl>








  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_Length_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Length*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_Length" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Length">
  Length
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public double Length { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd></dd>
  </dl>








  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_MidPoint_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.MidPoint*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_MidPoint" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.MidPoint">
  MidPoint
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Point3d MidPoint { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
  </dl>








  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_StartPoint_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.StartPoint*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_StartPoint" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.StartPoint">
  StartPoint
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Point3d StartPoint { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
  </dl>








  <h2 class="section" id="methods">Methods
</h2>


  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_BaryComb_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.BaryComb*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_BaryComb_System_Double_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.BaryComb(System.Double)">
  BaryComb(double)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Point3d BaryComb(double blendCoefficient)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>blendCoefficient</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_Create_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Create*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_Create_System_IntPtr_System_Boolean_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Create(System.IntPtr,System.Boolean)">
  Create(IntPtr, bool)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static LineSegment3d Create(IntPtr unmanagedPointer, bool autoDelete)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>unmanagedPointer</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.intptr">IntPtr</a></dt>
    <dd></dd>
    <dt><code>autoDelete</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.LineSegment3d.html">LineSegment3d</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_GetBisector_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.GetBisector*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_GetBisector" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.GetBisector">
  GetBisector()
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Plane GetBisector()</code></pre>
  </div>


  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Plane.html">Plane</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_Set_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Set*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_Set_Autodesk_AutoCAD_Geometry_Curve3d_Autodesk_AutoCAD_Geometry_Curve3d_System_Double_System_Double_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Set(Autodesk.AutoCAD.Geometry.Curve3d,Autodesk.AutoCAD.Geometry.Curve3d,System.Double,System.Double)">
  Set(Curve3d, Curve3d, double, double)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void Set(Curve3d curve1, Curve3d curve2, double parameter1, double parameter2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html">Curve3d</a></dt>
    <dd></dd>
    <dt><code>curve2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html">Curve3d</a></dt>
    <dd></dd>
    <dt><code>parameter1</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd></dd>
    <dt><code>parameter2</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_Set_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Set*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_Set_Autodesk_AutoCAD_Geometry_Curve3d_Autodesk_AutoCAD_Geometry_Point3d_System_Double_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Set(Autodesk.AutoCAD.Geometry.Curve3d,Autodesk.AutoCAD.Geometry.Point3d,System.Double)">
  Set(Curve3d, Point3d, double)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void Set(Curve3d curve, Point3d point, double parameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve3d.html">Curve3d</a></dt>
    <dd></dd>
    <dt><code>point</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
    <dt><code>parameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_Set_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Set*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_Set_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Point3d_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Set(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
  Set(Point3d, Point3d)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void Set(Point3d point1, Point3d point2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>point1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
    <dt><code>point2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_LineSegment3d_Set_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Set*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_LineSegment3d_Set_Autodesk_AutoCAD_Geometry_Point3d_Autodesk_AutoCAD_Geometry_Vector3d_" data-uid="Autodesk.AutoCAD.Geometry.LineSegment3d.Set(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Vector3d)">
  Set(Point3d, Vector3d)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void Set(Point3d point, Vector3d vector)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>point</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Point3d.html">Point3d</a></dt>
    <dd></dd>
    <dt><code>vector</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Vector3d.html">Vector3d</a></dt>
    <dd></dd>
  </dl>













</article>

        <div class="contribution d-print-none">
        </div>

        
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>

    <div class="container-xxl search-results" id="search-results"></div>

    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>
  </body>
</html>