<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class CurveCurveIntersector2d
 </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class CurveCurveIntersector2d
 ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../public/docfx.min.css">
      <link rel="stylesheet" href="../public/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      <meta name="docfx:rel" content="../">
      
      
      
  </head>

  <script type="module">
    import options from './../public/main.js'
    import { init } from './../public/docfx.min.js'
    init(options)
  </script>

  <script>
    const theme = localStorage.getItem('theme') || 'auto'
    document.documentElement.setAttribute('data-bs-theme', theme === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : theme)
  </script>


  <body class="tex2jax_ignore" data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../logo.svg" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navpanel" aria-controls="navpanel" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navpanel">
            <div id="navbar">
              <form class="search" role="search" id="search">
                <i class="bi bi-search"></i>
                <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
              </form>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d">



  <h1 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d" class="text-break">
    Class CurveCurveIntersector2d
  
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><a class="xref" href="Autodesk.html">Autodesk</a>.<a class="xref" href="Autodesk.AutoCAD.html">AutoCAD</a>.<a class="xref" href="Autodesk.AutoCAD.Geometry.html">Geometry</a></dd></dl>
  <dl><dt>Assembly</dt><dd>Acdbmgd.dll</dd></dl>
  </div>

  <div class="markdown summary"></div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[Wrapper(&quot;AcGeCurveCurveInt2d&quot;)]
public sealed class CurveCurveIntersector2d : Entity2d, IDisposable, ICloneable</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.marshalbyrefobject">MarshalByRefObject</a></div>
      <div><a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html">DisposableWrapper</a></div>
      <div><a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html">Entity2d</a></div>
      <div><span class="xref">CurveCurveIntersector2d</span></div>
    </dd>
  </dl>

  <dl class="typelist implements">
    <dt>Implements</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.idisposable">IDisposable</a></div>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.icloneable">ICloneable</a></div>
    </dd>
  </dl>


  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_Clone">Entity2d.Clone()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_IsEqualTo_Autodesk_AutoCAD_Geometry_Entity2d_">Entity2d.IsEqualTo(Entity2d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_IsEqualTo_Autodesk_AutoCAD_Geometry_Entity2d_Autodesk_AutoCAD_Geometry_Tolerance_">Entity2d.IsEqualTo(Entity2d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_TransformBy_Autodesk_AutoCAD_Geometry_Matrix2d_">Entity2d.TransformBy(Matrix2d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_TranslateBy_Autodesk_AutoCAD_Geometry_Vector2d_">Entity2d.TranslateBy(Vector2d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_RotateBy_System_Double_Autodesk_AutoCAD_Geometry_Point2d_">Entity2d.RotateBy(double, Point2d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_Mirror_Autodesk_AutoCAD_Geometry_Line2d_">Entity2d.Mirror(Line2d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_ScaleBy_System_Double_Autodesk_AutoCAD_Geometry_Point2d_">Entity2d.ScaleBy(double, Point2d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_IsOn_Autodesk_AutoCAD_Geometry_Point2d_">Entity2d.IsOn(Point2d)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Geometry.Entity2d.html#Autodesk_AutoCAD_Geometry_Entity2d_IsOn_Autodesk_AutoCAD_Geometry_Point2d_Autodesk_AutoCAD_Geometry_Tolerance_">Entity2d.IsOn(Point2d, Tolerance)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_Create_System_Type_System_IntPtr_System_Boolean_">DisposableWrapper.Create(Type, IntPtr, bool)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_Equals_System_Object_">DisposableWrapper.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_GetHashCode">DisposableWrapper.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_Dispose">DisposableWrapper.Dispose()</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_AutoDelete">DisposableWrapper.AutoDelete</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_IsDisposed">DisposableWrapper.IsDisposed</a>
    </div>
    <div>
      <a class="xref" href="Autodesk.AutoCAD.Runtime.DisposableWrapper.html#Autodesk_AutoCAD_Runtime_DisposableWrapper_UnmanagedObject">DisposableWrapper.UnmanagedObject</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.marshalbyrefobject.getlifetimeservice">MarshalByRefObject.GetLifetimeService()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.marshalbyrefobject.initializelifetimeservice">MarshalByRefObject.InitializeLifetimeService()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.marshalbyrefobject.createobjref">MarshalByRefObject.CreateObjRef(Type)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype">object.GetType()</a>
    </div>
  </dd></dl>

  <dl class="typelist extensionMethods">
    <dt>Extension Methods</dt>
    <dd>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD.Basal.ArgumentNullEx.NotNull``1(``0,System.String)">ArgumentNullEx.NotNull&lt;T&gt;(T, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD.Basal.ArgumentNullEx.NotNull``1(``0,System.String)">ArgumentNullEx.NotNull&lt;T&gt;(T, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD.Basal.ArgumentNullEx.NotNull``1(``0,System.String)">ArgumentNullEx.NotNull&lt;T&gt;(T, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD_Basal_ArgumentNullEx_NotNull_System_Object_System_String_">ArgumentNullEx.NotNull(object?, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD_Basal_ArgumentNullEx_NotNull_System_Object_System_String_">ArgumentNullEx.NotNull(object?, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.ArgumentNullEx.html#IFoxCAD_Basal_ArgumentNullEx_NotNull_System_Object_System_String_">ArgumentNullEx.NotNull(object?, string)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_GetProperty_System_Object_System_String_System_Object___">LateBinding.GetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_GetProperty_System_Object_System_String_System_Object___">LateBinding.GetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_GetProperty_System_Object_System_String_System_Object___">LateBinding.GetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_Invoke_System_Object_System_String_System_Object___">LateBinding.Invoke(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_Invoke_System_Object_System_String_System_Object___">LateBinding.Invoke(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_Invoke_System_Object_System_String_System_Object___">LateBinding.Invoke(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_ReleaseInstance_System_Object_">LateBinding.ReleaseInstance(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_ReleaseInstance_System_Object_">LateBinding.ReleaseInstance(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_ReleaseInstance_System_Object_">LateBinding.ReleaseInstance(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_SetProperty_System_Object_System_String_System_Object___">LateBinding.SetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_SetProperty_System_Object_System_String_System_Object___">LateBinding.SetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Basal.LateBinding.html#IFoxCAD_Basal_LateBinding_SetProperty_System_Object_System_String_System_Object___">LateBinding.SetProperty(object, string, params object[])</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_Print_System_Object_">ObjEx.Print(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_PrintLine_System_Object_">ObjEx.PrintLine(object)</a>
  </div>
  <div>
      <a class="xref" href="IFoxCAD.Cad.ObjEx.html#IFoxCAD_Cad_ObjEx_PrintLine_System_Object_">ObjEx.PrintLine(object)</a>
  </div>
  </dd></dl>





  <h2 class="section" id="constructors">Constructors
</h2>


  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor">
  CurveCurveIntersector2d()
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public CurveCurveIntersector2d()</code></pre>
  </div>













  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Curve2d_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor(Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Curve2d)">
  CurveCurveIntersector2d(Curve2d, Curve2d)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public CurveCurveIntersector2d(Curve2d curve1, Curve2d curve2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>curve2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Interval_Autodesk_AutoCAD_Geometry_Interval_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor(Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Interval,Autodesk.AutoCAD.Geometry.Interval)">
  CurveCurveIntersector2d(Curve2d, Curve2d, Interval, Interval)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public CurveCurveIntersector2d(Curve2d curve1, Curve2d curve2, Interval range1, Interval range2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>curve2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>range1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a></dt>
    <dd></dd>
    <dt><code>range2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Interval_Autodesk_AutoCAD_Geometry_Interval_Autodesk_AutoCAD_Geometry_Tolerance_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor(Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Interval,Autodesk.AutoCAD.Geometry.Interval,Autodesk.AutoCAD.Geometry.Tolerance)">
  CurveCurveIntersector2d(Curve2d, Curve2d, Interval, Interval, Tolerance)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public CurveCurveIntersector2d(Curve2d curve1, Curve2d curve2, Interval range1, Interval range2, Tolerance tolerance)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>curve2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>range1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a></dt>
    <dd></dd>
    <dt><code>range2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a></dt>
    <dd></dd>
    <dt><code>tolerance</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Tolerance.html">Tolerance</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d__ctor_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Tolerance_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.#ctor(Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Tolerance)">
  CurveCurveIntersector2d(Curve2d, Curve2d, Tolerance)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public CurveCurveIntersector2d(Curve2d curve1, Curve2d curve2, Tolerance tolerance)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>curve2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>tolerance</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Tolerance.html">Tolerance</a></dt>
    <dd></dd>
  </dl>












  <h2 class="section" id="properties">Properties
</h2>


  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Curve1_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Curve1*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Curve1" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Curve1">
  Curve1
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Curve2d Curve1 { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
  </dl>








  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Curve2_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Curve2*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Curve2" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Curve2">
  Curve2
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Curve2d Curve2 { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
  </dl>








  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_NumberOfIntersectionPoints_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.NumberOfIntersectionPoints*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_NumberOfIntersectionPoints" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.NumberOfIntersectionPoints">
  NumberOfIntersectionPoints
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public int NumberOfIntersectionPoints { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>








  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_OverlapCount_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.OverlapCount*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_OverlapCount" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.OverlapCount">
  OverlapCount
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public int OverlapCount { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>








  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_OverlapDirection_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.OverlapDirection*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_OverlapDirection" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.OverlapDirection">
  OverlapDirection
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public bool OverlapDirection { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd></dd>
  </dl>








  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Tolerance_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Tolerance*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Tolerance" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Tolerance">
  Tolerance
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Tolerance Tolerance { get; }</code></pre>
  </div>





  <h4 class="section">Property Value</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Tolerance.html">Tolerance</a></dt>
    <dd></dd>
  </dl>








  <h2 class="section" id="methods">Methods
</h2>


  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_ChangeCurveOrder_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.ChangeCurveOrder*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_ChangeCurveOrder" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.ChangeCurveOrder">
  ChangeCurveOrder()
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void ChangeCurveOrder()</code></pre>
  </div>













  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Create_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Create*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Create_System_IntPtr_System_Boolean_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Create(System.IntPtr,System.Boolean)">
  Create(IntPtr, bool)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static CurveCurveIntersector2d Create(IntPtr unmanagedPointer, bool autoDelete)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>unmanagedPointer</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.intptr">IntPtr</a></dt>
    <dd></dd>
    <dt><code>autoDelete</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.html">CurveCurveIntersector2d</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetIntersectionParameters_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetIntersectionParameters*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetIntersectionParameters_System_Int32_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetIntersectionParameters(System.Int32)">
  GetIntersectionParameters(int)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public double[] GetIntersectionParameters(int intersection)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>intersection</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a>[]</dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetIntersectionPoint_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetIntersectionPoint*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetIntersectionPoint_System_Int32_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetIntersectionPoint(System.Int32)">
  GetIntersectionPoint(int)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Point2d GetIntersectionPoint(int number)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>number</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Point2d.html">Point2d</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetIntersectionPointTolerance_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetIntersectionPointTolerance*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetIntersectionPointTolerance_System_Int32_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetIntersectionPointTolerance(System.Int32)">
  GetIntersectionPointTolerance(int)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public double GetIntersectionPointTolerance(int intersection)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>intersection</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetIntersectionRanges_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetIntersectionRanges*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetIntersectionRanges" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetIntersectionRanges">
  GetIntersectionRanges()
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Interval[] GetIntersectionRanges()</code></pre>
  </div>


  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a>[]</dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetOverlapRanges_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetOverlapRanges*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetOverlapRanges_System_Int32_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetOverlapRanges(System.Int32)">
  GetOverlapRanges(int)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public Interval[] GetOverlapRanges(int overlapNumber)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>overlapNumber</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a>[]</dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetPointOnCurve1_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetPointOnCurve1*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetPointOnCurve1_System_Int32_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetPointOnCurve1(System.Int32)">
  GetPointOnCurve1(int)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public PointOnCurve2d GetPointOnCurve1(int intersection)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>intersection</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.PointOnCurve2d.html">PointOnCurve2d</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetPointOnCurve2_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetPointOnCurve2*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_GetPointOnCurve2_System_Int32_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.GetPointOnCurve2(System.Int32)">
  GetPointOnCurve2(int)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public PointOnCurve2d GetPointOnCurve2(int intersection)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>intersection</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="Autodesk.AutoCAD.Geometry.PointOnCurve2d.html">PointOnCurve2d</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_IsTangential_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.IsTangential*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_IsTangential_System_Int32_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.IsTangential(System.Int32)">
  IsTangential(int)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public bool IsTangential(int intersection)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>intersection</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_IsTransversal_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.IsTransversal*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_IsTransversal_System_Int32_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.IsTransversal(System.Int32)">
  IsTransversal(int)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public bool IsTransversal(int intersection)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>intersection</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd></dd>
  </dl>











  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_OrderWithRegardsTo1_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.OrderWithRegardsTo1*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_OrderWithRegardsTo1" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.OrderWithRegardsTo1">
  OrderWithRegardsTo1()
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void OrderWithRegardsTo1()</code></pre>
  </div>













  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_OrderWithRegardsTo2_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.OrderWithRegardsTo2*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_OrderWithRegardsTo2" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.OrderWithRegardsTo2">
  OrderWithRegardsTo2()
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void OrderWithRegardsTo2()</code></pre>
  </div>













  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Set_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Set*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Set_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Curve2d_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Set(Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Curve2d)">
  Set(Curve2d, Curve2d)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void Set(Curve2d curve1, Curve2d curve2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>curve2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Set_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Set*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Set_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Interval_Autodesk_AutoCAD_Geometry_Interval_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Set(Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Interval,Autodesk.AutoCAD.Geometry.Interval)">
  Set(Curve2d, Curve2d, Interval, Interval)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void Set(Curve2d curve1, Curve2d curve2, Interval range1, Interval range2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>curve2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>range1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a></dt>
    <dd></dd>
    <dt><code>range2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Set_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Set*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Set_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Interval_Autodesk_AutoCAD_Geometry_Interval_Autodesk_AutoCAD_Geometry_Tolerance_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Set(Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Interval,Autodesk.AutoCAD.Geometry.Interval,Autodesk.AutoCAD.Geometry.Tolerance)">
  Set(Curve2d, Curve2d, Interval, Interval, Tolerance)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void Set(Curve2d curve1, Curve2d curve2, Interval range1, Interval range2, Tolerance tolerance)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>curve2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>range1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a></dt>
    <dd></dd>
    <dt><code>range2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Interval.html">Interval</a></dt>
    <dd></dd>
    <dt><code>tolerance</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Tolerance.html">Tolerance</a></dt>
    <dd></dd>
  </dl>












  <a id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Set_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Set*"></a>

  <h3 id="Autodesk_AutoCAD_Geometry_CurveCurveIntersector2d_Set_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Tolerance_" data-uid="Autodesk.AutoCAD.Geometry.CurveCurveIntersector2d.Set(Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Tolerance)">
  Set(Curve2d, Curve2d, Tolerance)
  
  </h3>

  <div class="markdown level1 summary"></div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public void Set(Curve2d curve1, Curve2d curve2, Tolerance tolerance)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve1</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>curve2</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Curve2d.html">Curve2d</a></dt>
    <dd></dd>
    <dt><code>tolerance</code> <a class="xref" href="Autodesk.AutoCAD.Geometry.Tolerance.html">Tolerance</a></dt>
    <dd></dd>
  </dl>













</article>

        <div class="contribution d-print-none">
        </div>

        
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>

    <div class="container-xxl search-results" id="search-results"></div>

    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>
  </body>
</html>