<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class Curve2dEx
 </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class Curve2dEx
 ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../public/docfx.min.css">
      <link rel="stylesheet" href="../public/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      
      
      
  </head>

  <script type="module">
    import options from './../public/main.js'
    import { init } from './../public/docfx.min.js'
    init(options)
  </script>

  <script>
    const theme = localStorage.getItem('theme') || 'auto'
    document.documentElement.setAttribute('data-bs-theme', theme === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : theme)
  </script>


  <body class="tex2jax_ignore" data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../logo.svg" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navpanel" aria-controls="navpanel" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navpanel">
            <div id="navbar">
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="IFoxCAD.Cad.Curve2dEx">



  <h1 id="IFoxCAD_Cad_Curve2dEx" data-uid="IFoxCAD.Cad.Curve2dEx" class="text-break">
    Class Curve2dEx
  
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><a class="xref" href="IFoxCAD.html">IFoxCAD</a>.<a class="xref" href="IFoxCAD.Cad.html">Cad</a></dd></dl>
  <dl><dt>Assembly</dt><dd>IFox.CAD.ACAD.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>二维解析类曲线转换为二维实体曲线扩展类</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static class Curve2dEx</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">Curve2dEx</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone">object.MemberwiseClone()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode">object.GetHashCode()</a>
    </div>
  </dd></dl>






  <h2 class="section" id="methods">Methods
</h2>


  <a id="IFoxCAD_Cad_Curve2dEx_IsIn_" data-uid="IFoxCAD.Cad.Curve2dEx.IsIn*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_IsIn_Autodesk_AutoCAD_Geometry_CircularArc2d_Autodesk_AutoCAD_Geometry_Point2d_" data-uid="IFoxCAD.Cad.Curve2dEx.IsIn(Autodesk.AutoCAD.Geometry.CircularArc2d,Autodesk.AutoCAD.Geometry.Point2d)">
  IsIn(CircularArc2d, Point2d)
  
  </h3>

  <div class="markdown level1 summary"><p>判断点是否位于圆内及圆上</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static bool IsIn(this CircularArc2d ca2d, Point2d pnt)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ca2d</code> <span class="xref">CircularArc2d</span></dt>
    <dd><p>二维解析类圆弧对象</p>
</dd>
    <dt><code>pnt</code> <span class="xref">Point2d</span></dt>
    <dd><p>二维点</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>位于圆内及圆上返回 <a href="https://learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/bool">true</a>,反之返回 <a href="https://learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/bool">false</a></p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToArc_" data-uid="IFoxCAD.Cad.Curve2dEx.ToArc*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToArc_Autodesk_AutoCAD_Geometry_CircularArc2d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToArc(Autodesk.AutoCAD.Geometry.CircularArc2d)">
  ToArc(CircularArc2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类圆弧转换为实体圆弧</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Arc ToArc(this CircularArc2d a2d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>a2d</code> <span class="xref">CircularArc2d</span></dt>
    <dd><p>二维解析类圆弧对象</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Arc</span></dt>
    <dd><p>圆弧</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCircle_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCircle*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCircle_Autodesk_AutoCAD_Geometry_CircularArc2d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCircle(Autodesk.AutoCAD.Geometry.CircularArc2d)">
  ToCircle(CircularArc2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类圆弧转换为实体圆</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Circle ToCircle(this CircularArc2d c2d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>c2d</code> <span class="xref">CircularArc2d</span></dt>
    <dd><p>二维解析类圆弧对象</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Circle</span></dt>
    <dd><p>实体圆</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_CircularArc2d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.CircularArc2d)">
  ToCurve(CircularArc2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类圆弧转换为实体圆或者圆弧</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Curve ToCurve(this CircularArc2d ca2d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ca2d</code> <span class="xref">CircularArc2d</span></dt>
    <dd><p>二维解析类圆弧对象</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Curve</span></dt>
    <dd><p>实体圆或者圆弧</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_CircularArc2d_Autodesk_AutoCAD_Geometry_Matrix3d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.CircularArc2d,Autodesk.AutoCAD.Geometry.Matrix3d)">
  ToCurve(CircularArc2d, Matrix3d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类圆弧转换为实体圆或者圆弧，然后进行矩阵变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Curve ToCurve(this CircularArc2d ca2d, Matrix3d mat)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ca2d</code> <span class="xref">CircularArc2d</span></dt>
    <dd><p>二维解析类圆弧对象</p>
</dd>
    <dt><code>mat</code> <span class="xref">Matrix3d</span></dt>
    <dd><p>变换矩阵</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Curve</span></dt>
    <dd><p>实体圆或者圆弧</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_Curve2d_Autodesk_AutoCAD_Geometry_Matrix3d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.Curve2d,Autodesk.AutoCAD.Geometry.Matrix3d)">
  ToCurve(Curve2d, Matrix3d)
  
  </h3>

  <div class="markdown level1 summary"><p>按矩阵转换Ge2d曲线为Db曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Curve? ToCurve(this Curve2d curve, Matrix3d mat)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>curve</code> <span class="xref">Curve2d</span></dt>
    <dd><p>Ge2d曲线</p>
</dd>
    <dt><code>mat</code> <span class="xref">Matrix3d</span></dt>
    <dd><p>曲线转换矩阵</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Curve</span></dt>
    <dd><p>Db曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_EllipticalArc2d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.EllipticalArc2d)">
  ToCurve(EllipticalArc2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类椭圆弧转换为实体椭圆弧</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Ellipse ToCurve(this EllipticalArc2d ea2d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ea2d</code> <span class="xref">EllipticalArc2d</span></dt>
    <dd><p>二维解析类椭圆弧对象</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Ellipse</span></dt>
    <dd><p>实体椭圆弧</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_EllipticalArc2d_Autodesk_AutoCAD_Geometry_Matrix3d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.EllipticalArc2d,Autodesk.AutoCAD.Geometry.Matrix3d)">
  ToCurve(EllipticalArc2d, Matrix3d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类椭圆弧转换为实体椭圆弧，然后进行矩阵变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Ellipse ToCurve(this EllipticalArc2d ea2d, Matrix3d mat)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ea2d</code> <span class="xref">EllipticalArc2d</span></dt>
    <dd><p>二维解析类椭圆弧对象</p>
</dd>
    <dt><code>mat</code> <span class="xref">Matrix3d</span></dt>
    <dd><p>变换矩阵</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Ellipse</span></dt>
    <dd><p>实体椭圆弧</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_Line2d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.Line2d)">
  ToCurve(Line2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类直线转换为实体类构造线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Xline ToCurve(this Line2d line2d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>line2d</code> <span class="xref">Line2d</span></dt>
    <dd><p>二维解析类直线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Xline</span></dt>
    <dd><p>实体类构造线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_Line2d_Autodesk_AutoCAD_Geometry_Matrix3d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.Line2d,Autodesk.AutoCAD.Geometry.Matrix3d)">
  ToCurve(Line2d, Matrix3d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类直线转换为实体类构造线，然后进行矩阵变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Xline ToCurve(this Line2d line2d, Matrix3d mat)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>line2d</code> <span class="xref">Line2d</span></dt>
    <dd><p>二维解析类直线</p>
</dd>
    <dt><code>mat</code> <span class="xref">Matrix3d</span></dt>
    <dd><p>变换矩阵</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Xline</span></dt>
    <dd><p>实体类构造线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_LineSegment2d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.LineSegment2d)">
  ToCurve(LineSegment2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类线段转换为实体类直线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Line ToCurve(this LineSegment2d ls2d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ls2d</code> <span class="xref">LineSegment2d</span></dt>
    <dd><p>二维解析类线段</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Line</span></dt>
    <dd><p>实体类直线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_LineSegment2d_Autodesk_AutoCAD_Geometry_Matrix3d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.LineSegment2d,Autodesk.AutoCAD.Geometry.Matrix3d)">
  ToCurve(LineSegment2d, Matrix3d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类线段转换为实体类直线，并进行矩阵变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Line ToCurve(this LineSegment2d ls2d, Matrix3d mat)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ls2d</code> <span class="xref">LineSegment2d</span></dt>
    <dd><p>二维解析类线段</p>
</dd>
    <dt><code>mat</code> <span class="xref">Matrix3d</span></dt>
    <dd><p>变换矩阵</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Line</span></dt>
    <dd><p>实体类直线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_NurbCurve2d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.NurbCurve2d)">
  ToCurve(NurbCurve2d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类BURB曲线转换为实体类样条曲线</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Spline ToCurve(this NurbCurve2d nc2d)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>nc2d</code> <span class="xref">NurbCurve2d</span></dt>
    <dd><p>二维解析类BURB曲线</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Spline</span></dt>
    <dd><p>实体类样条曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToCurve_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToCurve_Autodesk_AutoCAD_Geometry_NurbCurve2d_Autodesk_AutoCAD_Geometry_Matrix3d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToCurve(Autodesk.AutoCAD.Geometry.NurbCurve2d,Autodesk.AutoCAD.Geometry.Matrix3d)">
  ToCurve(NurbCurve2d, Matrix3d)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类BURB曲线转换为实体类样条曲线，并进行矩阵变换</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Spline ToCurve(this NurbCurve2d nc2d, Matrix3d mat)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>nc2d</code> <span class="xref">NurbCurve2d</span></dt>
    <dd><p>二维解析类BURB曲线</p>
</dd>
    <dt><code>mat</code> <span class="xref">Matrix3d</span></dt>
    <dd><p>变换矩阵</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Spline</span></dt>
    <dd><p>实体类样条曲线</p>
</dd>
  </dl>











  <a id="IFoxCAD_Cad_Curve2dEx_ToLineSegment2d_" data-uid="IFoxCAD.Cad.Curve2dEx.ToLineSegment2d*"></a>

  <h3 id="IFoxCAD_Cad_Curve2dEx_ToLineSegment2d_Autodesk_AutoCAD_Geometry_Line2d_System_Double_System_Double_" data-uid="IFoxCAD.Cad.Curve2dEx.ToLineSegment2d(Autodesk.AutoCAD.Geometry.Line2d,System.Double,System.Double)">
  ToLineSegment2d(Line2d, double, double)
  
  </h3>

  <div class="markdown level1 summary"><p>将二维解析类构造线转换为二维解析类线段</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static LineSegment2d ToLineSegment2d(this Line2d line2d, double fromParameter, double toParameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>line2d</code> <span class="xref">Line2d</span></dt>
    <dd><p>二维解析类构造线</p>
</dd>
    <dt><code>fromParameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>起点参数</p>
</dd>
    <dt><code>toParameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>终点参数</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">LineSegment2d</span></dt>
    <dd><p>二维解析类线段</p>
</dd>
  </dl>












</article>

        <div class="contribution d-print-none">
        </div>

        
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>
  </body>
</html>